#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HRM")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTbl_Attendance(Tbl_Attendance instance);
    partial void UpdateTbl_Attendance(Tbl_Attendance instance);
    partial void DeleteTbl_Attendance(Tbl_Attendance instance);
    partial void InsertTbl_UserRegistartion(Tbl_UserRegistartion instance);
    partial void UpdateTbl_UserRegistartion(Tbl_UserRegistartion instance);
    partial void DeleteTbl_UserRegistartion(Tbl_UserRegistartion instance);
    partial void InsertTbl_EmpEduDetail(Tbl_EmpEduDetail instance);
    partial void UpdateTbl_EmpEduDetail(Tbl_EmpEduDetail instance);
    partial void DeleteTbl_EmpEduDetail(Tbl_EmpEduDetail instance);
    partial void InsertTbl_EmpLeave(Tbl_EmpLeave instance);
    partial void UpdateTbl_EmpLeave(Tbl_EmpLeave instance);
    partial void DeleteTbl_EmpLeave(Tbl_EmpLeave instance);
    partial void InsertTbl_EmployeeRegistration(Tbl_EmployeeRegistration instance);
    partial void UpdateTbl_EmployeeRegistration(Tbl_EmployeeRegistration instance);
    partial void DeleteTbl_EmployeeRegistration(Tbl_EmployeeRegistration instance);
    partial void InsertTbl_Payroll(Tbl_Payroll instance);
    partial void UpdateTbl_Payroll(Tbl_Payroll instance);
    partial void DeleteTbl_Payroll(Tbl_Payroll instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HRMConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Attendance> Tbl_Attendances
		{
			get
			{
				return this.GetTable<Tbl_Attendance>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_UserRegistartion> Tbl_UserRegistartions
		{
			get
			{
				return this.GetTable<Tbl_UserRegistartion>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_EmpEduDetail> Tbl_EmpEduDetails
		{
			get
			{
				return this.GetTable<Tbl_EmpEduDetail>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_EmpLeave> Tbl_EmpLeaves
		{
			get
			{
				return this.GetTable<Tbl_EmpLeave>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_EmployeeRegistration> Tbl_EmployeeRegistrations
		{
			get
			{
				return this.GetTable<Tbl_EmployeeRegistration>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Payroll> Tbl_Payrolls
		{
			get
			{
				return this.GetTable<Tbl_Payroll>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Attendance")]
	public partial class Tbl_Attendance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DetailId;
		
		private System.Nullable<int> _Emp_ID;
		
		private System.Nullable<System.DateTime> _ClockIn;
		
		private System.Nullable<System.DateTime> _ClockOut;
		
		private System.Nullable<System.DateTime> _breakstart;
		
		private System.Nullable<System.DateTime> _breakend;
		
		private System.Nullable<double> _totalbreak;
		
		private System.Nullable<System.DateTime> _Date;
		
		private string _btnstart;
		
		private string _btnend;
		
		private EntityRef<Tbl_EmployeeRegistration> _Tbl_EmployeeRegistration;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetailIdChanging(int value);
    partial void OnDetailIdChanged();
    partial void OnEmp_IDChanging(System.Nullable<int> value);
    partial void OnEmp_IDChanged();
    partial void OnClockInChanging(System.Nullable<System.DateTime> value);
    partial void OnClockInChanged();
    partial void OnClockOutChanging(System.Nullable<System.DateTime> value);
    partial void OnClockOutChanged();
    partial void OnbreakstartChanging(System.Nullable<System.DateTime> value);
    partial void OnbreakstartChanged();
    partial void OnbreakendChanging(System.Nullable<System.DateTime> value);
    partial void OnbreakendChanged();
    partial void OntotalbreakChanging(System.Nullable<double> value);
    partial void OntotalbreakChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnbtnstartChanging(string value);
    partial void OnbtnstartChanged();
    partial void OnbtnendChanging(string value);
    partial void OnbtnendChanged();
    #endregion
		
		public Tbl_Attendance()
		{
			this._Tbl_EmployeeRegistration = default(EntityRef<Tbl_EmployeeRegistration>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int DetailId
		{
			get
			{
				return this._DetailId;
			}
			set
			{
				if ((this._DetailId != value))
				{
					this.OnDetailIdChanging(value);
					this.SendPropertyChanging();
					this._DetailId = value;
					this.SendPropertyChanged("DetailId");
					this.OnDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_ID", DbType="Int")]
		public System.Nullable<int> Emp_ID
		{
			get
			{
				return this._Emp_ID;
			}
			set
			{
				if ((this._Emp_ID != value))
				{
					if (this._Tbl_EmployeeRegistration.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmp_IDChanging(value);
					this.SendPropertyChanging();
					this._Emp_ID = value;
					this.SendPropertyChanged("Emp_ID");
					this.OnEmp_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClockIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClockIn
		{
			get
			{
				return this._ClockIn;
			}
			set
			{
				if ((this._ClockIn != value))
				{
					this.OnClockInChanging(value);
					this.SendPropertyChanging();
					this._ClockIn = value;
					this.SendPropertyChanged("ClockIn");
					this.OnClockInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClockOut", DbType="DateTime")]
		public System.Nullable<System.DateTime> ClockOut
		{
			get
			{
				return this._ClockOut;
			}
			set
			{
				if ((this._ClockOut != value))
				{
					this.OnClockOutChanging(value);
					this.SendPropertyChanging();
					this._ClockOut = value;
					this.SendPropertyChanged("ClockOut");
					this.OnClockOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_breakstart", DbType="DateTime")]
		public System.Nullable<System.DateTime> breakstart
		{
			get
			{
				return this._breakstart;
			}
			set
			{
				if ((this._breakstart != value))
				{
					this.OnbreakstartChanging(value);
					this.SendPropertyChanging();
					this._breakstart = value;
					this.SendPropertyChanged("breakstart");
					this.OnbreakstartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_breakend", DbType="DateTime")]
		public System.Nullable<System.DateTime> breakend
		{
			get
			{
				return this._breakend;
			}
			set
			{
				if ((this._breakend != value))
				{
					this.OnbreakendChanging(value);
					this.SendPropertyChanging();
					this._breakend = value;
					this.SendPropertyChanged("breakend");
					this.OnbreakendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalbreak", DbType="Float")]
		public System.Nullable<double> totalbreak
		{
			get
			{
				return this._totalbreak;
			}
			set
			{
				if ((this._totalbreak != value))
				{
					this.OntotalbreakChanging(value);
					this.SendPropertyChanging();
					this._totalbreak = value;
					this.SendPropertyChanged("totalbreak");
					this.OntotalbreakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_btnstart", DbType="NChar(10)")]
		public string btnstart
		{
			get
			{
				return this._btnstart;
			}
			set
			{
				if ((this._btnstart != value))
				{
					this.OnbtnstartChanging(value);
					this.SendPropertyChanging();
					this._btnstart = value;
					this.SendPropertyChanged("btnstart");
					this.OnbtnstartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_btnend", DbType="NChar(10)")]
		public string btnend
		{
			get
			{
				return this._btnend;
			}
			set
			{
				if ((this._btnend != value))
				{
					this.OnbtnendChanging(value);
					this.SendPropertyChanging();
					this._btnend = value;
					this.SendPropertyChanged("btnend");
					this.OnbtnendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_EmployeeRegistration_Tbl_Attendance", Storage="_Tbl_EmployeeRegistration", ThisKey="Emp_ID", OtherKey="Emp_id", IsForeignKey=true)]
		public Tbl_EmployeeRegistration Tbl_EmployeeRegistration
		{
			get
			{
				return this._Tbl_EmployeeRegistration.Entity;
			}
			set
			{
				Tbl_EmployeeRegistration previousValue = this._Tbl_EmployeeRegistration.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_EmployeeRegistration.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_EmployeeRegistration.Entity = null;
						previousValue.Tbl_Attendances.Remove(this);
					}
					this._Tbl_EmployeeRegistration.Entity = value;
					if ((value != null))
					{
						value.Tbl_Attendances.Add(this);
						this._Emp_ID = value.Emp_id;
					}
					else
					{
						this._Emp_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_EmployeeRegistration");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_UserRegistartion")]
	public partial class Tbl_UserRegistartion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _username;
		
		private string _Password;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Tbl_UserRegistartion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NChar(20)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(10)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_EmpEduDetails")]
	public partial class Tbl_EmpEduDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Detail_Id;
		
		private System.Nullable<int> _Emp_id;
		
		private string _PG_Colgname;
		
		private string _PG_Universityname;
		
		private string _PG_State;
		
		private string _PG_City;
		
		private string _PG_yearofPassing;
		
		private string _PGMarks;
		
		private string _G_colgname;
		
		private string _G_University;
		
		private string _G_State;
		
		private string _G_City;
		
		private string _G_yearOfPassing;
		
		private string _G_marks;
		
		private string @__12_ColgName;
		
		private string @__12_Board;
		
		private string @__12_State;
		
		private string @__12_City;
		
		private string @__12_yearofpassing;
		
		private string @__12_marks;
		
		private string _school_name;
		
		private string _Board_name;
		
		private string _S_state;
		
		private string _S_City;
		
		private string _S_yaerofpassing;
		
		private string _S_Marks;
		
		private EntityRef<Tbl_EmployeeRegistration> _Tbl_EmployeeRegistration;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetail_IdChanging(int value);
    partial void OnDetail_IdChanged();
    partial void OnEmp_idChanging(System.Nullable<int> value);
    partial void OnEmp_idChanged();
    partial void OnPG_ColgnameChanging(string value);
    partial void OnPG_ColgnameChanged();
    partial void OnPG_UniversitynameChanging(string value);
    partial void OnPG_UniversitynameChanged();
    partial void OnPG_StateChanging(string value);
    partial void OnPG_StateChanged();
    partial void OnPG_CityChanging(string value);
    partial void OnPG_CityChanged();
    partial void OnPG_yearofPassingChanging(string value);
    partial void OnPG_yearofPassingChanged();
    partial void OnPGMarksChanging(string value);
    partial void OnPGMarksChanged();
    partial void OnG_colgnameChanging(string value);
    partial void OnG_colgnameChanged();
    partial void OnG_UniversityChanging(string value);
    partial void OnG_UniversityChanged();
    partial void OnG_StateChanging(string value);
    partial void OnG_StateChanged();
    partial void OnG_CityChanging(string value);
    partial void OnG_CityChanged();
    partial void OnG_yearOfPassingChanging(string value);
    partial void OnG_yearOfPassingChanged();
    partial void OnG_marksChanging(string value);
    partial void OnG_marksChanged();
    partial void On_12_ColgNameChanging(string value);
    partial void On_12_ColgNameChanged();
    partial void On_12_BoardChanging(string value);
    partial void On_12_BoardChanged();
    partial void On_12_StateChanging(string value);
    partial void On_12_StateChanged();
    partial void On_12_CityChanging(string value);
    partial void On_12_CityChanged();
    partial void On_12_yearofpassingChanging(string value);
    partial void On_12_yearofpassingChanged();
    partial void On_12_marksChanging(string value);
    partial void On_12_marksChanged();
    partial void Onschool_nameChanging(string value);
    partial void Onschool_nameChanged();
    partial void OnBoard_nameChanging(string value);
    partial void OnBoard_nameChanged();
    partial void OnS_stateChanging(string value);
    partial void OnS_stateChanged();
    partial void OnS_CityChanging(string value);
    partial void OnS_CityChanged();
    partial void OnS_yaerofpassingChanging(string value);
    partial void OnS_yaerofpassingChanged();
    partial void OnS_MarksChanging(string value);
    partial void OnS_MarksChanged();
    #endregion
		
		public Tbl_EmpEduDetail()
		{
			this._Tbl_EmployeeRegistration = default(EntityRef<Tbl_EmployeeRegistration>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Detail_Id
		{
			get
			{
				return this._Detail_Id;
			}
			set
			{
				if ((this._Detail_Id != value))
				{
					this.OnDetail_IdChanging(value);
					this.SendPropertyChanging();
					this._Detail_Id = value;
					this.SendPropertyChanged("Detail_Id");
					this.OnDetail_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_id", DbType="Int")]
		public System.Nullable<int> Emp_id
		{
			get
			{
				return this._Emp_id;
			}
			set
			{
				if ((this._Emp_id != value))
				{
					if (this._Tbl_EmployeeRegistration.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmp_idChanging(value);
					this.SendPropertyChanging();
					this._Emp_id = value;
					this.SendPropertyChanged("Emp_id");
					this.OnEmp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PG_Colgname", DbType="NVarChar(MAX)")]
		public string PG_Colgname
		{
			get
			{
				return this._PG_Colgname;
			}
			set
			{
				if ((this._PG_Colgname != value))
				{
					this.OnPG_ColgnameChanging(value);
					this.SendPropertyChanging();
					this._PG_Colgname = value;
					this.SendPropertyChanged("PG_Colgname");
					this.OnPG_ColgnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PG_Universityname", DbType="NVarChar(MAX)")]
		public string PG_Universityname
		{
			get
			{
				return this._PG_Universityname;
			}
			set
			{
				if ((this._PG_Universityname != value))
				{
					this.OnPG_UniversitynameChanging(value);
					this.SendPropertyChanging();
					this._PG_Universityname = value;
					this.SendPropertyChanged("PG_Universityname");
					this.OnPG_UniversitynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PG_State", DbType="NChar(20)")]
		public string PG_State
		{
			get
			{
				return this._PG_State;
			}
			set
			{
				if ((this._PG_State != value))
				{
					this.OnPG_StateChanging(value);
					this.SendPropertyChanging();
					this._PG_State = value;
					this.SendPropertyChanged("PG_State");
					this.OnPG_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PG_City", DbType="NChar(20)")]
		public string PG_City
		{
			get
			{
				return this._PG_City;
			}
			set
			{
				if ((this._PG_City != value))
				{
					this.OnPG_CityChanging(value);
					this.SendPropertyChanging();
					this._PG_City = value;
					this.SendPropertyChanged("PG_City");
					this.OnPG_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PG_yearofPassing", DbType="NChar(30)")]
		public string PG_yearofPassing
		{
			get
			{
				return this._PG_yearofPassing;
			}
			set
			{
				if ((this._PG_yearofPassing != value))
				{
					this.OnPG_yearofPassingChanging(value);
					this.SendPropertyChanging();
					this._PG_yearofPassing = value;
					this.SendPropertyChanged("PG_yearofPassing");
					this.OnPG_yearofPassingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PGMarks", DbType="NChar(10)")]
		public string PGMarks
		{
			get
			{
				return this._PGMarks;
			}
			set
			{
				if ((this._PGMarks != value))
				{
					this.OnPGMarksChanging(value);
					this.SendPropertyChanging();
					this._PGMarks = value;
					this.SendPropertyChanged("PGMarks");
					this.OnPGMarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_colgname", DbType="NVarChar(MAX)")]
		public string G_colgname
		{
			get
			{
				return this._G_colgname;
			}
			set
			{
				if ((this._G_colgname != value))
				{
					this.OnG_colgnameChanging(value);
					this.SendPropertyChanging();
					this._G_colgname = value;
					this.SendPropertyChanged("G_colgname");
					this.OnG_colgnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_University", DbType="NVarChar(MAX)")]
		public string G_University
		{
			get
			{
				return this._G_University;
			}
			set
			{
				if ((this._G_University != value))
				{
					this.OnG_UniversityChanging(value);
					this.SendPropertyChanging();
					this._G_University = value;
					this.SendPropertyChanged("G_University");
					this.OnG_UniversityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_State", DbType="NChar(20)")]
		public string G_State
		{
			get
			{
				return this._G_State;
			}
			set
			{
				if ((this._G_State != value))
				{
					this.OnG_StateChanging(value);
					this.SendPropertyChanging();
					this._G_State = value;
					this.SendPropertyChanged("G_State");
					this.OnG_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_City", DbType="NChar(20)")]
		public string G_City
		{
			get
			{
				return this._G_City;
			}
			set
			{
				if ((this._G_City != value))
				{
					this.OnG_CityChanging(value);
					this.SendPropertyChanging();
					this._G_City = value;
					this.SendPropertyChanged("G_City");
					this.OnG_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_yearOfPassing", DbType="NChar(20)")]
		public string G_yearOfPassing
		{
			get
			{
				return this._G_yearOfPassing;
			}
			set
			{
				if ((this._G_yearOfPassing != value))
				{
					this.OnG_yearOfPassingChanging(value);
					this.SendPropertyChanging();
					this._G_yearOfPassing = value;
					this.SendPropertyChanged("G_yearOfPassing");
					this.OnG_yearOfPassingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_G_marks", DbType="NChar(10)")]
		public string G_marks
		{
			get
			{
				return this._G_marks;
			}
			set
			{
				if ((this._G_marks != value))
				{
					this.OnG_marksChanging(value);
					this.SendPropertyChanging();
					this._G_marks = value;
					this.SendPropertyChanged("G_marks");
					this.OnG_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[12_ColgName]", Storage="__12_ColgName", DbType="NVarChar(MAX)")]
		public string _12_ColgName
		{
			get
			{
				return this.@__12_ColgName;
			}
			set
			{
				if ((this.@__12_ColgName != value))
				{
					this.On_12_ColgNameChanging(value);
					this.SendPropertyChanging();
					this.@__12_ColgName = value;
					this.SendPropertyChanged("_12_ColgName");
					this.On_12_ColgNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[12_Board]", Storage="__12_Board", DbType="NChar(30)")]
		public string _12_Board
		{
			get
			{
				return this.@__12_Board;
			}
			set
			{
				if ((this.@__12_Board != value))
				{
					this.On_12_BoardChanging(value);
					this.SendPropertyChanging();
					this.@__12_Board = value;
					this.SendPropertyChanged("_12_Board");
					this.On_12_BoardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[12_State]", Storage="__12_State", DbType="NChar(20)")]
		public string _12_State
		{
			get
			{
				return this.@__12_State;
			}
			set
			{
				if ((this.@__12_State != value))
				{
					this.On_12_StateChanging(value);
					this.SendPropertyChanging();
					this.@__12_State = value;
					this.SendPropertyChanged("_12_State");
					this.On_12_StateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[12_City]", Storage="__12_City", DbType="NChar(20)")]
		public string _12_City
		{
			get
			{
				return this.@__12_City;
			}
			set
			{
				if ((this.@__12_City != value))
				{
					this.On_12_CityChanging(value);
					this.SendPropertyChanging();
					this.@__12_City = value;
					this.SendPropertyChanged("_12_City");
					this.On_12_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[12_yearofpassing]", Storage="__12_yearofpassing", DbType="NChar(20)")]
		public string _12_yearofpassing
		{
			get
			{
				return this.@__12_yearofpassing;
			}
			set
			{
				if ((this.@__12_yearofpassing != value))
				{
					this.On_12_yearofpassingChanging(value);
					this.SendPropertyChanging();
					this.@__12_yearofpassing = value;
					this.SendPropertyChanged("_12_yearofpassing");
					this.On_12_yearofpassingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[12_marks]", Storage="__12_marks", DbType="NChar(10)")]
		public string _12_marks
		{
			get
			{
				return this.@__12_marks;
			}
			set
			{
				if ((this.@__12_marks != value))
				{
					this.On_12_marksChanging(value);
					this.SendPropertyChanging();
					this.@__12_marks = value;
					this.SendPropertyChanged("_12_marks");
					this.On_12_marksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_school_name", DbType="NVarChar(MAX)")]
		public string school_name
		{
			get
			{
				return this._school_name;
			}
			set
			{
				if ((this._school_name != value))
				{
					this.Onschool_nameChanging(value);
					this.SendPropertyChanging();
					this._school_name = value;
					this.SendPropertyChanged("school_name");
					this.Onschool_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Board_name", DbType="NChar(20)")]
		public string Board_name
		{
			get
			{
				return this._Board_name;
			}
			set
			{
				if ((this._Board_name != value))
				{
					this.OnBoard_nameChanging(value);
					this.SendPropertyChanging();
					this._Board_name = value;
					this.SendPropertyChanged("Board_name");
					this.OnBoard_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_state", DbType="NChar(20)")]
		public string S_state
		{
			get
			{
				return this._S_state;
			}
			set
			{
				if ((this._S_state != value))
				{
					this.OnS_stateChanging(value);
					this.SendPropertyChanging();
					this._S_state = value;
					this.SendPropertyChanged("S_state");
					this.OnS_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_City", DbType="NChar(20)")]
		public string S_City
		{
			get
			{
				return this._S_City;
			}
			set
			{
				if ((this._S_City != value))
				{
					this.OnS_CityChanging(value);
					this.SendPropertyChanging();
					this._S_City = value;
					this.SendPropertyChanged("S_City");
					this.OnS_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_yaerofpassing", DbType="NChar(20)")]
		public string S_yaerofpassing
		{
			get
			{
				return this._S_yaerofpassing;
			}
			set
			{
				if ((this._S_yaerofpassing != value))
				{
					this.OnS_yaerofpassingChanging(value);
					this.SendPropertyChanging();
					this._S_yaerofpassing = value;
					this.SendPropertyChanged("S_yaerofpassing");
					this.OnS_yaerofpassingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Marks", DbType="NChar(20)")]
		public string S_Marks
		{
			get
			{
				return this._S_Marks;
			}
			set
			{
				if ((this._S_Marks != value))
				{
					this.OnS_MarksChanging(value);
					this.SendPropertyChanging();
					this._S_Marks = value;
					this.SendPropertyChanged("S_Marks");
					this.OnS_MarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_EmployeeRegistration_Tbl_EmpEduDetail", Storage="_Tbl_EmployeeRegistration", ThisKey="Emp_id", OtherKey="Emp_id", IsForeignKey=true)]
		public Tbl_EmployeeRegistration Tbl_EmployeeRegistration
		{
			get
			{
				return this._Tbl_EmployeeRegistration.Entity;
			}
			set
			{
				Tbl_EmployeeRegistration previousValue = this._Tbl_EmployeeRegistration.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_EmployeeRegistration.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_EmployeeRegistration.Entity = null;
						previousValue.Tbl_EmpEduDetails.Remove(this);
					}
					this._Tbl_EmployeeRegistration.Entity = value;
					if ((value != null))
					{
						value.Tbl_EmpEduDetails.Add(this);
						this._Emp_id = value.Emp_id;
					}
					else
					{
						this._Emp_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_EmployeeRegistration");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_EmpLeaves")]
	public partial class Tbl_EmpLeave : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LeaveDetailId;
		
		private System.Nullable<int> _Emp_Id;
		
		private string _LeaveType;
		
		private System.Nullable<System.DateTime> _From_Date;
		
		private System.Nullable<System.DateTime> _ToDate;
		
		private System.Nullable<System.DateTime> _Date;
		
		private string _Comment;
		
		private System.Nullable<int> _Stetus;
		
		private EntityRef<Tbl_EmployeeRegistration> _Tbl_EmployeeRegistration;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLeaveDetailIdChanging(int value);
    partial void OnLeaveDetailIdChanged();
    partial void OnEmp_IdChanging(System.Nullable<int> value);
    partial void OnEmp_IdChanged();
    partial void OnLeaveTypeChanging(string value);
    partial void OnLeaveTypeChanged();
    partial void OnFrom_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnFrom_DateChanged();
    partial void OnToDateChanging(System.Nullable<System.DateTime> value);
    partial void OnToDateChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnStetusChanging(System.Nullable<int> value);
    partial void OnStetusChanged();
    #endregion
		
		public Tbl_EmpLeave()
		{
			this._Tbl_EmployeeRegistration = default(EntityRef<Tbl_EmployeeRegistration>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveDetailId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int LeaveDetailId
		{
			get
			{
				return this._LeaveDetailId;
			}
			set
			{
				if ((this._LeaveDetailId != value))
				{
					this.OnLeaveDetailIdChanging(value);
					this.SendPropertyChanging();
					this._LeaveDetailId = value;
					this.SendPropertyChanged("LeaveDetailId");
					this.OnLeaveDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Id", DbType="Int")]
		public System.Nullable<int> Emp_Id
		{
			get
			{
				return this._Emp_Id;
			}
			set
			{
				if ((this._Emp_Id != value))
				{
					if (this._Tbl_EmployeeRegistration.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmp_IdChanging(value);
					this.SendPropertyChanging();
					this._Emp_Id = value;
					this.SendPropertyChanged("Emp_Id");
					this.OnEmp_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveType", DbType="NChar(20)")]
		public string LeaveType
		{
			get
			{
				return this._LeaveType;
			}
			set
			{
				if ((this._LeaveType != value))
				{
					this.OnLeaveTypeChanging(value);
					this.SendPropertyChanging();
					this._LeaveType = value;
					this.SendPropertyChanged("LeaveType");
					this.OnLeaveTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> From_Date
		{
			get
			{
				return this._From_Date;
			}
			set
			{
				if ((this._From_Date != value))
				{
					this.OnFrom_DateChanging(value);
					this.SendPropertyChanging();
					this._From_Date = value;
					this.SendPropertyChanged("From_Date");
					this.OnFrom_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ToDate
		{
			get
			{
				return this._ToDate;
			}
			set
			{
				if ((this._ToDate != value))
				{
					this.OnToDateChanging(value);
					this.SendPropertyChanging();
					this._ToDate = value;
					this.SendPropertyChanged("ToDate");
					this.OnToDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stetus", DbType="Int")]
		public System.Nullable<int> Stetus
		{
			get
			{
				return this._Stetus;
			}
			set
			{
				if ((this._Stetus != value))
				{
					this.OnStetusChanging(value);
					this.SendPropertyChanging();
					this._Stetus = value;
					this.SendPropertyChanged("Stetus");
					this.OnStetusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_EmployeeRegistration_Tbl_EmpLeave", Storage="_Tbl_EmployeeRegistration", ThisKey="Emp_Id", OtherKey="Emp_id", IsForeignKey=true)]
		public Tbl_EmployeeRegistration Tbl_EmployeeRegistration
		{
			get
			{
				return this._Tbl_EmployeeRegistration.Entity;
			}
			set
			{
				Tbl_EmployeeRegistration previousValue = this._Tbl_EmployeeRegistration.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_EmployeeRegistration.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_EmployeeRegistration.Entity = null;
						previousValue.Tbl_EmpLeaves.Remove(this);
					}
					this._Tbl_EmployeeRegistration.Entity = value;
					if ((value != null))
					{
						value.Tbl_EmpLeaves.Add(this);
						this._Emp_Id = value.Emp_id;
					}
					else
					{
						this._Emp_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_EmployeeRegistration");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_EmployeeRegistration")]
	public partial class Tbl_EmployeeRegistration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Emp_id;
		
		private string _Emp_Name;
		
		private string _Emp_FatherName;
		
		private System.Nullable<System.DateTime> _Emp_DOJ;
		
		private string _Emp_Passport_No;
		
		private string _Emp_Mobile;
		
		private string _Emp_Homeno;
		
		private string _PanNo;
		
		private string _EmailId;
		
		private System.Nullable<System.DateTime> _Emp_DOB;
		
		private string _Designation;
		
		private string _Gender;
		
		private string _MeritialStetus;
		
		private string _Department;
		
		private System.Nullable<double> _BasicSalary;
		
		private string _UserName;
		
		private string _Password;
		
		private string _BankAccountName;
		
		private string _AccountNo;
		
		private string _BankName;
		
		private string _BranchName;
		
		private string _IFSCcode;
		
		private string _profilepath;
		
		private System.Nullable<System.DateTime> _Date;
		
		private string _Resume;
		
		private string _OfferLetter;
		
		private string _JoiningLetter;
		
		private string _PanCard;
		
		private string _AadharCard;
		
		private string _AddressProof;
		
		private string _passport;
		
		private string _resumetype;
		
		private string _offerLext;
		
		private string _joiningext;
		
		private EntitySet<Tbl_Attendance> _Tbl_Attendances;
		
		private EntitySet<Tbl_EmpEduDetail> _Tbl_EmpEduDetails;
		
		private EntitySet<Tbl_EmpLeave> _Tbl_EmpLeaves;
		
		private EntitySet<Tbl_Payroll> _Tbl_Payrolls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmp_idChanging(int value);
    partial void OnEmp_idChanged();
    partial void OnEmp_NameChanging(string value);
    partial void OnEmp_NameChanged();
    partial void OnEmp_FatherNameChanging(string value);
    partial void OnEmp_FatherNameChanged();
    partial void OnEmp_DOJChanging(System.Nullable<System.DateTime> value);
    partial void OnEmp_DOJChanged();
    partial void OnEmp_Passport_NoChanging(string value);
    partial void OnEmp_Passport_NoChanged();
    partial void OnEmp_MobileChanging(string value);
    partial void OnEmp_MobileChanged();
    partial void OnEmp_HomenoChanging(string value);
    partial void OnEmp_HomenoChanged();
    partial void OnPanNoChanging(string value);
    partial void OnPanNoChanged();
    partial void OnEmailIdChanging(string value);
    partial void OnEmailIdChanged();
    partial void OnEmp_DOBChanging(System.Nullable<System.DateTime> value);
    partial void OnEmp_DOBChanged();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnMeritialStetusChanging(string value);
    partial void OnMeritialStetusChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnBasicSalaryChanging(System.Nullable<double> value);
    partial void OnBasicSalaryChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnBankAccountNameChanging(string value);
    partial void OnBankAccountNameChanged();
    partial void OnAccountNoChanging(string value);
    partial void OnAccountNoChanged();
    partial void OnBankNameChanging(string value);
    partial void OnBankNameChanged();
    partial void OnBranchNameChanging(string value);
    partial void OnBranchNameChanged();
    partial void OnIFSCcodeChanging(string value);
    partial void OnIFSCcodeChanged();
    partial void OnprofilepathChanging(string value);
    partial void OnprofilepathChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnResumeChanging(string value);
    partial void OnResumeChanged();
    partial void OnOfferLetterChanging(string value);
    partial void OnOfferLetterChanged();
    partial void OnJoiningLetterChanging(string value);
    partial void OnJoiningLetterChanged();
    partial void OnPanCardChanging(string value);
    partial void OnPanCardChanged();
    partial void OnAadharCardChanging(string value);
    partial void OnAadharCardChanged();
    partial void OnAddressProofChanging(string value);
    partial void OnAddressProofChanged();
    partial void OnpassportChanging(string value);
    partial void OnpassportChanged();
    partial void OnresumetypeChanging(string value);
    partial void OnresumetypeChanged();
    partial void OnofferLextChanging(string value);
    partial void OnofferLextChanged();
    partial void OnjoiningextChanging(string value);
    partial void OnjoiningextChanged();
    #endregion
		
		public Tbl_EmployeeRegistration()
		{
			this._Tbl_Attendances = new EntitySet<Tbl_Attendance>(new Action<Tbl_Attendance>(this.attach_Tbl_Attendances), new Action<Tbl_Attendance>(this.detach_Tbl_Attendances));
			this._Tbl_EmpEduDetails = new EntitySet<Tbl_EmpEduDetail>(new Action<Tbl_EmpEduDetail>(this.attach_Tbl_EmpEduDetails), new Action<Tbl_EmpEduDetail>(this.detach_Tbl_EmpEduDetails));
			this._Tbl_EmpLeaves = new EntitySet<Tbl_EmpLeave>(new Action<Tbl_EmpLeave>(this.attach_Tbl_EmpLeaves), new Action<Tbl_EmpLeave>(this.detach_Tbl_EmpLeaves));
			this._Tbl_Payrolls = new EntitySet<Tbl_Payroll>(new Action<Tbl_Payroll>(this.attach_Tbl_Payrolls), new Action<Tbl_Payroll>(this.detach_Tbl_Payrolls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Emp_id
		{
			get
			{
				return this._Emp_id;
			}
			set
			{
				if ((this._Emp_id != value))
				{
					this.OnEmp_idChanging(value);
					this.SendPropertyChanging();
					this._Emp_id = value;
					this.SendPropertyChanged("Emp_id");
					this.OnEmp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Name", DbType="NChar(20)")]
		public string Emp_Name
		{
			get
			{
				return this._Emp_Name;
			}
			set
			{
				if ((this._Emp_Name != value))
				{
					this.OnEmp_NameChanging(value);
					this.SendPropertyChanging();
					this._Emp_Name = value;
					this.SendPropertyChanged("Emp_Name");
					this.OnEmp_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_FatherName", DbType="NChar(20)")]
		public string Emp_FatherName
		{
			get
			{
				return this._Emp_FatherName;
			}
			set
			{
				if ((this._Emp_FatherName != value))
				{
					this.OnEmp_FatherNameChanging(value);
					this.SendPropertyChanging();
					this._Emp_FatherName = value;
					this.SendPropertyChanged("Emp_FatherName");
					this.OnEmp_FatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_DOJ", DbType="Date")]
		public System.Nullable<System.DateTime> Emp_DOJ
		{
			get
			{
				return this._Emp_DOJ;
			}
			set
			{
				if ((this._Emp_DOJ != value))
				{
					this.OnEmp_DOJChanging(value);
					this.SendPropertyChanging();
					this._Emp_DOJ = value;
					this.SendPropertyChanged("Emp_DOJ");
					this.OnEmp_DOJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Passport_No", DbType="NChar(30)")]
		public string Emp_Passport_No
		{
			get
			{
				return this._Emp_Passport_No;
			}
			set
			{
				if ((this._Emp_Passport_No != value))
				{
					this.OnEmp_Passport_NoChanging(value);
					this.SendPropertyChanging();
					this._Emp_Passport_No = value;
					this.SendPropertyChanged("Emp_Passport_No");
					this.OnEmp_Passport_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Mobile", DbType="NChar(15)")]
		public string Emp_Mobile
		{
			get
			{
				return this._Emp_Mobile;
			}
			set
			{
				if ((this._Emp_Mobile != value))
				{
					this.OnEmp_MobileChanging(value);
					this.SendPropertyChanging();
					this._Emp_Mobile = value;
					this.SendPropertyChanged("Emp_Mobile");
					this.OnEmp_MobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_Homeno", DbType="NChar(15)")]
		public string Emp_Homeno
		{
			get
			{
				return this._Emp_Homeno;
			}
			set
			{
				if ((this._Emp_Homeno != value))
				{
					this.OnEmp_HomenoChanging(value);
					this.SendPropertyChanging();
					this._Emp_Homeno = value;
					this.SendPropertyChanged("Emp_Homeno");
					this.OnEmp_HomenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PanNo", DbType="NChar(30)")]
		public string PanNo
		{
			get
			{
				return this._PanNo;
			}
			set
			{
				if ((this._PanNo != value))
				{
					this.OnPanNoChanging(value);
					this.SendPropertyChanging();
					this._PanNo = value;
					this.SendPropertyChanged("PanNo");
					this.OnPanNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailId", DbType="NChar(50)")]
		public string EmailId
		{
			get
			{
				return this._EmailId;
			}
			set
			{
				if ((this._EmailId != value))
				{
					this.OnEmailIdChanging(value);
					this.SendPropertyChanging();
					this._EmailId = value;
					this.SendPropertyChanged("EmailId");
					this.OnEmailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emp_DOB", DbType="Date")]
		public System.Nullable<System.DateTime> Emp_DOB
		{
			get
			{
				return this._Emp_DOB;
			}
			set
			{
				if ((this._Emp_DOB != value))
				{
					this.OnEmp_DOBChanging(value);
					this.SendPropertyChanging();
					this._Emp_DOB = value;
					this.SendPropertyChanged("Emp_DOB");
					this.OnEmp_DOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="NChar(20)")]
		public string Designation
		{
			get
			{
				return this._Designation;
			}
			set
			{
				if ((this._Designation != value))
				{
					this.OnDesignationChanging(value);
					this.SendPropertyChanging();
					this._Designation = value;
					this.SendPropertyChanged("Designation");
					this.OnDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NChar(10)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MeritialStetus", DbType="NChar(10)")]
		public string MeritialStetus
		{
			get
			{
				return this._MeritialStetus;
			}
			set
			{
				if ((this._MeritialStetus != value))
				{
					this.OnMeritialStetusChanging(value);
					this.SendPropertyChanging();
					this._MeritialStetus = value;
					this.SendPropertyChanged("MeritialStetus");
					this.OnMeritialStetusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="NChar(20)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicSalary", DbType="Float")]
		public System.Nullable<double> BasicSalary
		{
			get
			{
				return this._BasicSalary;
			}
			set
			{
				if ((this._BasicSalary != value))
				{
					this.OnBasicSalaryChanging(value);
					this.SendPropertyChanging();
					this._BasicSalary = value;
					this.SendPropertyChanged("BasicSalary");
					this.OnBasicSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NChar(20)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(20)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccountName", DbType="NChar(20)")]
		public string BankAccountName
		{
			get
			{
				return this._BankAccountName;
			}
			set
			{
				if ((this._BankAccountName != value))
				{
					this.OnBankAccountNameChanging(value);
					this.SendPropertyChanging();
					this._BankAccountName = value;
					this.SendPropertyChanged("BankAccountName");
					this.OnBankAccountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo", DbType="NChar(20)")]
		public string AccountNo
		{
			get
			{
				return this._AccountNo;
			}
			set
			{
				if ((this._AccountNo != value))
				{
					this.OnAccountNoChanging(value);
					this.SendPropertyChanging();
					this._AccountNo = value;
					this.SendPropertyChanged("AccountNo");
					this.OnAccountNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="NChar(20)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this.OnBankNameChanging(value);
					this.SendPropertyChanging();
					this._BankName = value;
					this.SendPropertyChanged("BankName");
					this.OnBankNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchName", DbType="NChar(30)")]
		public string BranchName
		{
			get
			{
				return this._BranchName;
			}
			set
			{
				if ((this._BranchName != value))
				{
					this.OnBranchNameChanging(value);
					this.SendPropertyChanging();
					this._BranchName = value;
					this.SendPropertyChanged("BranchName");
					this.OnBranchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFSCcode", DbType="NChar(20)")]
		public string IFSCcode
		{
			get
			{
				return this._IFSCcode;
			}
			set
			{
				if ((this._IFSCcode != value))
				{
					this.OnIFSCcodeChanging(value);
					this.SendPropertyChanging();
					this._IFSCcode = value;
					this.SendPropertyChanged("IFSCcode");
					this.OnIFSCcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profilepath", DbType="NVarChar(MAX)")]
		public string profilepath
		{
			get
			{
				return this._profilepath;
			}
			set
			{
				if ((this._profilepath != value))
				{
					this.OnprofilepathChanging(value);
					this.SendPropertyChanging();
					this._profilepath = value;
					this.SendPropertyChanged("profilepath");
					this.OnprofilepathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resume", DbType="NVarChar(MAX)")]
		public string Resume
		{
			get
			{
				return this._Resume;
			}
			set
			{
				if ((this._Resume != value))
				{
					this.OnResumeChanging(value);
					this.SendPropertyChanging();
					this._Resume = value;
					this.SendPropertyChanged("Resume");
					this.OnResumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfferLetter", DbType="NVarChar(MAX)")]
		public string OfferLetter
		{
			get
			{
				return this._OfferLetter;
			}
			set
			{
				if ((this._OfferLetter != value))
				{
					this.OnOfferLetterChanging(value);
					this.SendPropertyChanging();
					this._OfferLetter = value;
					this.SendPropertyChanged("OfferLetter");
					this.OnOfferLetterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoiningLetter", DbType="NVarChar(MAX)")]
		public string JoiningLetter
		{
			get
			{
				return this._JoiningLetter;
			}
			set
			{
				if ((this._JoiningLetter != value))
				{
					this.OnJoiningLetterChanging(value);
					this.SendPropertyChanging();
					this._JoiningLetter = value;
					this.SendPropertyChanged("JoiningLetter");
					this.OnJoiningLetterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PanCard", DbType="NVarChar(MAX)")]
		public string PanCard
		{
			get
			{
				return this._PanCard;
			}
			set
			{
				if ((this._PanCard != value))
				{
					this.OnPanCardChanging(value);
					this.SendPropertyChanging();
					this._PanCard = value;
					this.SendPropertyChanged("PanCard");
					this.OnPanCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AadharCard", DbType="NVarChar(MAX)")]
		public string AadharCard
		{
			get
			{
				return this._AadharCard;
			}
			set
			{
				if ((this._AadharCard != value))
				{
					this.OnAadharCardChanging(value);
					this.SendPropertyChanging();
					this._AadharCard = value;
					this.SendPropertyChanged("AadharCard");
					this.OnAadharCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressProof", DbType="NVarChar(MAX)")]
		public string AddressProof
		{
			get
			{
				return this._AddressProof;
			}
			set
			{
				if ((this._AddressProof != value))
				{
					this.OnAddressProofChanging(value);
					this.SendPropertyChanging();
					this._AddressProof = value;
					this.SendPropertyChanged("AddressProof");
					this.OnAddressProofChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passport", DbType="NVarChar(MAX)")]
		public string passport
		{
			get
			{
				return this._passport;
			}
			set
			{
				if ((this._passport != value))
				{
					this.OnpassportChanging(value);
					this.SendPropertyChanging();
					this._passport = value;
					this.SendPropertyChanged("passport");
					this.OnpassportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resumetype", DbType="NChar(10)")]
		public string resumetype
		{
			get
			{
				return this._resumetype;
			}
			set
			{
				if ((this._resumetype != value))
				{
					this.OnresumetypeChanging(value);
					this.SendPropertyChanging();
					this._resumetype = value;
					this.SendPropertyChanged("resumetype");
					this.OnresumetypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_offerLext", DbType="NChar(10)")]
		public string offerLext
		{
			get
			{
				return this._offerLext;
			}
			set
			{
				if ((this._offerLext != value))
				{
					this.OnofferLextChanging(value);
					this.SendPropertyChanging();
					this._offerLext = value;
					this.SendPropertyChanged("offerLext");
					this.OnofferLextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_joiningext", DbType="NChar(10)")]
		public string joiningext
		{
			get
			{
				return this._joiningext;
			}
			set
			{
				if ((this._joiningext != value))
				{
					this.OnjoiningextChanging(value);
					this.SendPropertyChanging();
					this._joiningext = value;
					this.SendPropertyChanged("joiningext");
					this.OnjoiningextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_EmployeeRegistration_Tbl_Attendance", Storage="_Tbl_Attendances", ThisKey="Emp_id", OtherKey="Emp_ID")]
		public EntitySet<Tbl_Attendance> Tbl_Attendances
		{
			get
			{
				return this._Tbl_Attendances;
			}
			set
			{
				this._Tbl_Attendances.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_EmployeeRegistration_Tbl_EmpEduDetail", Storage="_Tbl_EmpEduDetails", ThisKey="Emp_id", OtherKey="Emp_id")]
		public EntitySet<Tbl_EmpEduDetail> Tbl_EmpEduDetails
		{
			get
			{
				return this._Tbl_EmpEduDetails;
			}
			set
			{
				this._Tbl_EmpEduDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_EmployeeRegistration_Tbl_EmpLeave", Storage="_Tbl_EmpLeaves", ThisKey="Emp_id", OtherKey="Emp_Id")]
		public EntitySet<Tbl_EmpLeave> Tbl_EmpLeaves
		{
			get
			{
				return this._Tbl_EmpLeaves;
			}
			set
			{
				this._Tbl_EmpLeaves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_EmployeeRegistration_Tbl_Payroll", Storage="_Tbl_Payrolls", ThisKey="Emp_id", OtherKey="EmpID")]
		public EntitySet<Tbl_Payroll> Tbl_Payrolls
		{
			get
			{
				return this._Tbl_Payrolls;
			}
			set
			{
				this._Tbl_Payrolls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Attendances(Tbl_Attendance entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_EmployeeRegistration = this;
		}
		
		private void detach_Tbl_Attendances(Tbl_Attendance entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_EmployeeRegistration = null;
		}
		
		private void attach_Tbl_EmpEduDetails(Tbl_EmpEduDetail entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_EmployeeRegistration = this;
		}
		
		private void detach_Tbl_EmpEduDetails(Tbl_EmpEduDetail entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_EmployeeRegistration = null;
		}
		
		private void attach_Tbl_EmpLeaves(Tbl_EmpLeave entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_EmployeeRegistration = this;
		}
		
		private void detach_Tbl_EmpLeaves(Tbl_EmpLeave entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_EmployeeRegistration = null;
		}
		
		private void attach_Tbl_Payrolls(Tbl_Payroll entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_EmployeeRegistration = this;
		}
		
		private void detach_Tbl_Payrolls(Tbl_Payroll entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_EmployeeRegistration = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Payroll")]
	public partial class Tbl_Payroll : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PayrollID;
		
		private System.Nullable<int> _EmpID;
		
		private System.Nullable<System.DateTime> _Datefrom;
		
		private System.Nullable<System.DateTime> _Dateto;
		
		private System.Nullable<double> _BasicSalary;
		
		private System.Nullable<int> _TotalDays;
		
		private System.Nullable<int> _PresentDays;
		
		private System.Nullable<int> _leavdays;
		
		private System.Nullable<double> _salaryperday;
		
		private System.Nullable<double> _otherpay;
		
		private System.Nullable<double> _TotalPay;
		
		private System.Nullable<double> _LeaveDeduction;
		
		private System.Nullable<double> _ProfTax;
		
		private System.Nullable<double> _OtherDeduction;
		
		private System.Nullable<double> _TotalEarning;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<double> _TDS;
		
		private string _TotalEarninginword;
		
		private EntityRef<Tbl_EmployeeRegistration> _Tbl_EmployeeRegistration;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPayrollIDChanging(int value);
    partial void OnPayrollIDChanged();
    partial void OnEmpIDChanging(System.Nullable<int> value);
    partial void OnEmpIDChanged();
    partial void OnDatefromChanging(System.Nullable<System.DateTime> value);
    partial void OnDatefromChanged();
    partial void OnDatetoChanging(System.Nullable<System.DateTime> value);
    partial void OnDatetoChanged();
    partial void OnBasicSalaryChanging(System.Nullable<double> value);
    partial void OnBasicSalaryChanged();
    partial void OnTotalDaysChanging(System.Nullable<int> value);
    partial void OnTotalDaysChanged();
    partial void OnPresentDaysChanging(System.Nullable<int> value);
    partial void OnPresentDaysChanged();
    partial void OnleavdaysChanging(System.Nullable<int> value);
    partial void OnleavdaysChanged();
    partial void OnsalaryperdayChanging(System.Nullable<double> value);
    partial void OnsalaryperdayChanged();
    partial void OnotherpayChanging(System.Nullable<double> value);
    partial void OnotherpayChanged();
    partial void OnTotalPayChanging(System.Nullable<double> value);
    partial void OnTotalPayChanged();
    partial void OnLeaveDeductionChanging(System.Nullable<double> value);
    partial void OnLeaveDeductionChanged();
    partial void OnProfTaxChanging(System.Nullable<double> value);
    partial void OnProfTaxChanged();
    partial void OnOtherDeductionChanging(System.Nullable<double> value);
    partial void OnOtherDeductionChanged();
    partial void OnTotalEarningChanging(System.Nullable<double> value);
    partial void OnTotalEarningChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnTDSChanging(System.Nullable<double> value);
    partial void OnTDSChanged();
    partial void OnTotalEarninginwordChanging(string value);
    partial void OnTotalEarninginwordChanged();
    #endregion
		
		public Tbl_Payroll()
		{
			this._Tbl_EmployeeRegistration = default(EntityRef<Tbl_EmployeeRegistration>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayrollID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PayrollID
		{
			get
			{
				return this._PayrollID;
			}
			set
			{
				if ((this._PayrollID != value))
				{
					this.OnPayrollIDChanging(value);
					this.SendPropertyChanging();
					this._PayrollID = value;
					this.SendPropertyChanged("PayrollID");
					this.OnPayrollIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpID", DbType="Int")]
		public System.Nullable<int> EmpID
		{
			get
			{
				return this._EmpID;
			}
			set
			{
				if ((this._EmpID != value))
				{
					if (this._Tbl_EmployeeRegistration.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnEmpIDChanging(value);
					this.SendPropertyChanging();
					this._EmpID = value;
					this.SendPropertyChanged("EmpID");
					this.OnEmpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datefrom", DbType="DateTime")]
		public System.Nullable<System.DateTime> Datefrom
		{
			get
			{
				return this._Datefrom;
			}
			set
			{
				if ((this._Datefrom != value))
				{
					this.OnDatefromChanging(value);
					this.SendPropertyChanging();
					this._Datefrom = value;
					this.SendPropertyChanged("Datefrom");
					this.OnDatefromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dateto", DbType="DateTime")]
		public System.Nullable<System.DateTime> Dateto
		{
			get
			{
				return this._Dateto;
			}
			set
			{
				if ((this._Dateto != value))
				{
					this.OnDatetoChanging(value);
					this.SendPropertyChanging();
					this._Dateto = value;
					this.SendPropertyChanged("Dateto");
					this.OnDatetoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicSalary", DbType="Float")]
		public System.Nullable<double> BasicSalary
		{
			get
			{
				return this._BasicSalary;
			}
			set
			{
				if ((this._BasicSalary != value))
				{
					this.OnBasicSalaryChanging(value);
					this.SendPropertyChanging();
					this._BasicSalary = value;
					this.SendPropertyChanged("BasicSalary");
					this.OnBasicSalaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalDays", DbType="Int")]
		public System.Nullable<int> TotalDays
		{
			get
			{
				return this._TotalDays;
			}
			set
			{
				if ((this._TotalDays != value))
				{
					this.OnTotalDaysChanging(value);
					this.SendPropertyChanging();
					this._TotalDays = value;
					this.SendPropertyChanged("TotalDays");
					this.OnTotalDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PresentDays", DbType="Int")]
		public System.Nullable<int> PresentDays
		{
			get
			{
				return this._PresentDays;
			}
			set
			{
				if ((this._PresentDays != value))
				{
					this.OnPresentDaysChanging(value);
					this.SendPropertyChanging();
					this._PresentDays = value;
					this.SendPropertyChanged("PresentDays");
					this.OnPresentDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leavdays", DbType="Int")]
		public System.Nullable<int> leavdays
		{
			get
			{
				return this._leavdays;
			}
			set
			{
				if ((this._leavdays != value))
				{
					this.OnleavdaysChanging(value);
					this.SendPropertyChanging();
					this._leavdays = value;
					this.SendPropertyChanged("leavdays");
					this.OnleavdaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaryperday", DbType="Float")]
		public System.Nullable<double> salaryperday
		{
			get
			{
				return this._salaryperday;
			}
			set
			{
				if ((this._salaryperday != value))
				{
					this.OnsalaryperdayChanging(value);
					this.SendPropertyChanging();
					this._salaryperday = value;
					this.SendPropertyChanged("salaryperday");
					this.OnsalaryperdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_otherpay", DbType="Float")]
		public System.Nullable<double> otherpay
		{
			get
			{
				return this._otherpay;
			}
			set
			{
				if ((this._otherpay != value))
				{
					this.OnotherpayChanging(value);
					this.SendPropertyChanging();
					this._otherpay = value;
					this.SendPropertyChanged("otherpay");
					this.OnotherpayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPay", DbType="Float")]
		public System.Nullable<double> TotalPay
		{
			get
			{
				return this._TotalPay;
			}
			set
			{
				if ((this._TotalPay != value))
				{
					this.OnTotalPayChanging(value);
					this.SendPropertyChanging();
					this._TotalPay = value;
					this.SendPropertyChanged("TotalPay");
					this.OnTotalPayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LeaveDeduction", DbType="Float")]
		public System.Nullable<double> LeaveDeduction
		{
			get
			{
				return this._LeaveDeduction;
			}
			set
			{
				if ((this._LeaveDeduction != value))
				{
					this.OnLeaveDeductionChanging(value);
					this.SendPropertyChanging();
					this._LeaveDeduction = value;
					this.SendPropertyChanged("LeaveDeduction");
					this.OnLeaveDeductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProfTax", DbType="Float")]
		public System.Nullable<double> ProfTax
		{
			get
			{
				return this._ProfTax;
			}
			set
			{
				if ((this._ProfTax != value))
				{
					this.OnProfTaxChanging(value);
					this.SendPropertyChanging();
					this._ProfTax = value;
					this.SendPropertyChanged("ProfTax");
					this.OnProfTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherDeduction", DbType="Float")]
		public System.Nullable<double> OtherDeduction
		{
			get
			{
				return this._OtherDeduction;
			}
			set
			{
				if ((this._OtherDeduction != value))
				{
					this.OnOtherDeductionChanging(value);
					this.SendPropertyChanging();
					this._OtherDeduction = value;
					this.SendPropertyChanged("OtherDeduction");
					this.OnOtherDeductionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalEarning", DbType="Float")]
		public System.Nullable<double> TotalEarning
		{
			get
			{
				return this._TotalEarning;
			}
			set
			{
				if ((this._TotalEarning != value))
				{
					this.OnTotalEarningChanging(value);
					this.SendPropertyChanging();
					this._TotalEarning = value;
					this.SendPropertyChanged("TotalEarning");
					this.OnTotalEarningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TDS", DbType="Float")]
		public System.Nullable<double> TDS
		{
			get
			{
				return this._TDS;
			}
			set
			{
				if ((this._TDS != value))
				{
					this.OnTDSChanging(value);
					this.SendPropertyChanging();
					this._TDS = value;
					this.SendPropertyChanged("TDS");
					this.OnTDSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalEarninginword", DbType="NVarChar(MAX)")]
		public string TotalEarninginword
		{
			get
			{
				return this._TotalEarninginword;
			}
			set
			{
				if ((this._TotalEarninginword != value))
				{
					this.OnTotalEarninginwordChanging(value);
					this.SendPropertyChanging();
					this._TotalEarninginword = value;
					this.SendPropertyChanged("TotalEarninginword");
					this.OnTotalEarninginwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_EmployeeRegistration_Tbl_Payroll", Storage="_Tbl_EmployeeRegistration", ThisKey="EmpID", OtherKey="Emp_id", IsForeignKey=true)]
		public Tbl_EmployeeRegistration Tbl_EmployeeRegistration
		{
			get
			{
				return this._Tbl_EmployeeRegistration.Entity;
			}
			set
			{
				Tbl_EmployeeRegistration previousValue = this._Tbl_EmployeeRegistration.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_EmployeeRegistration.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_EmployeeRegistration.Entity = null;
						previousValue.Tbl_Payrolls.Remove(this);
					}
					this._Tbl_EmployeeRegistration.Entity = value;
					if ((value != null))
					{
						value.Tbl_Payrolls.Add(this);
						this._EmpID = value.Emp_id;
					}
					else
					{
						this._EmpID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_EmployeeRegistration");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
