//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExampleService.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add car: {0}..
        /// </summary>
        internal static string AddCar {
            get {
                return ResourceManager.GetString("AddCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address query..
        /// </summary>
        internal static string AddressQuery {
            get {
                return ResourceManager.GetString("AddressQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allready authorised..
        /// </summary>
        internal static string AllreadyAuthorised {
            get {
                return ResourceManager.GetString("AllreadyAuthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send answer..
        /// </summary>
        internal static string AnswerSendingFailed {
            get {
                return ResourceManager.GetString("AnswerSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer sent..
        /// </summary>
        internal static string AnswerSent {
            get {
                return ResourceManager.GetString("AnswerSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorisation code: {0}..
        /// </summary>
        internal static string AuthorisationCode {
            get {
                return ResourceManager.GetString("AuthorisationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorisation failed..
        /// </summary>
        internal static string AuthorisationFailed {
            get {
                return ResourceManager.GetString("AuthorisationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorisation success..
        /// </summary>
        internal static string AuthorisationSuccess {
            get {
                return ResourceManager.GetString("AuthorisationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVR version: {0}..
        /// </summary>
        internal static string AvrVersion {
            get {
                return ResourceManager.GetString("AvrVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad coordinates..
        /// </summary>
        internal static string BadCoordinates {
            get {
                return ResourceManager.GetString("BadCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad format..
        /// </summary>
        internal static string BadFormat {
            get {
                return ResourceManager.GetString("BadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad signature..
        /// </summary>
        internal static string BadSignature {
            get {
                return ResourceManager.GetString("BadSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad time..
        /// </summary>
        internal static string BadTime {
            get {
                return ResourceManager.GetString("BadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer length: {0}, offset: {1}, packet size: {2}..
        /// </summary>
        internal static string BufferInfo {
            get {
                return ResourceManager.GetString("BufferInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car created..
        /// </summary>
        internal static string CarCreated {
            get {
                return ResourceManager.GetString("CarCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking ip..
        /// </summary>
        internal static string CheckingIP {
            get {
                return ResourceManager.GetString("CheckingIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum: {0}..
        /// </summary>
        internal static string Checksum {
            get {
                return ResourceManager.GetString("Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command completed..
        /// </summary>
        internal static string CommandCompleted {
            get {
                return ResourceManager.GetString("CommandCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command found: {0}..
        /// </summary>
        internal static string CommandFound {
            get {
                return ResourceManager.GetString("CommandFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM port: {0}..
        /// </summary>
        internal static string ComPort {
            get {
                return ResourceManager.GetString("ComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB error..
        /// </summary>
        internal static string DbError {
            get {
                return ResourceManager.GetString("DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device allready exists: {0}..
        /// </summary>
        internal static string DeviceAllreadyExists {
            get {
                return ResourceManager.GetString("DeviceAllreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device created..
        /// </summary>
        internal static string DeviceCreated {
            get {
                return ResourceManager.GetString("DeviceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device doesn&apos;t exist: {0}..
        /// </summary>
        internal static string DeviceDoesntExist {
            get {
                return ResourceManager.GetString("DeviceDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device updated: {0}..
        /// </summary>
        internal static string DeviceUpdated {
            get {
                return ResourceManager.GetString("DeviceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code: {0}..
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File sent..
        /// </summary>
        internal static string FileSent {
            get {
                return ResourceManager.GetString("FileSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware select failed..
        /// </summary>
        internal static string FirmwareFailed {
            get {
                return ResourceManager.GetString("FirmwareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output: {0} ({1} l), input: {2} ({3} l).
        /// </summary>
        internal static string FuelInputOutput {
            get {
                return ResourceManager.GetString("FuelInputOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got file..
        /// </summary>
        internal static string GotFile {
            get {
                return ResourceManager.GetString("GotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID accepted..
        /// </summary>
        internal static string IdAccepted {
            get {
                return ResourceManager.GetString("IdAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID not found..
        /// </summary>
        internal static string IdNotFound {
            get {
                return ResourceManager.GetString("IdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID rejected..
        /// </summary>
        internal static string IdRejected {
            get {
                return ResourceManager.GetString("IdRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI accepted..
        /// </summary>
        internal static string ImeiOK {
            get {
                return ResourceManager.GetString("ImeiOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input: {0}..
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input, l: {0}..
        /// </summary>
        internal static string InputL {
            get {
                return ResourceManager.GetString("InputL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP check failed..
        /// </summary>
        internal static string IPCheckFailed {
            get {
                return ResourceManager.GetString("IPCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP check passed..
        /// </summary>
        internal static string IPCheckPassed {
            get {
                return ResourceManager.GetString("IPCheckPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key accepted..
        /// </summary>
        internal static string KeyAccepted {
            get {
                return ResourceManager.GetString("KeyAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received key: {0}..
        /// </summary>
        internal static string KeyReceived {
            get {
                return ResourceManager.GetString("KeyReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key rejected..
        /// </summary>
        internal static string KeyRejected {
            get {
                return ResourceManager.GetString("KeyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length sent..
        /// </summary>
        internal static string LengthSent {
            get {
                return ResourceManager.GetString("LengthSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map rendered per {0}..
        /// </summary>
        internal static string MapGeneratedPerTime {
            get {
                return ResourceManager.GetString("MapGeneratedPerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map query..
        /// </summary>
        internal static string MapQuery {
            get {
                return ResourceManager.GetString("MapQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map render error..
        /// </summary>
        internal static string MapRenderError {
            get {
                return ResourceManager.GetString("MapRenderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message not sent..
        /// </summary>
        internal static string MessageNotSent {
            get {
                return ResourceManager.GetString("MessageNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent..
        /// </summary>
        internal static string MessageSent {
            get {
                return ResourceManager.GetString("MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type: {0}..
        /// </summary>
        internal static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authorisation object...
        /// </summary>
        internal static string NoAuthorisationObject {
            get {
                return ResourceManager.GetString("NoAuthorisationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI don&apos;t exist..
        /// </summary>
        internal static string NoSuchImei {
            get {
                return ResourceManager.GetString("NoSuchImei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such type..
        /// </summary>
        internal static string NoSuchType {
            get {
                return ResourceManager.GetString("NoSuchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not assigned to car..
        /// </summary>
        internal static string NotAssignedToCar {
            get {
                return ResourceManager.GetString("NotAssignedToCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorised..
        /// </summary>
        internal static string NotAuthorised {
            get {
                return ResourceManager.GetString("NotAuthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output: {0}..
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output, l: {0}..
        /// </summary>
        internal static string OutputL {
            get {
                return ResourceManager.GetString("OutputL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet size: {0}..
        /// </summary>
        internal static string PacketSize {
            get {
                return ResourceManager.GetString("PacketSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Packet type: {1}..
        /// </summary>
        internal static string PacketType {
            get {
                return ResourceManager.GetString("PacketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing failed..
        /// </summary>
        internal static string ParsingFailed {
            get {
                return ResourceManager.GetString("ParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN: {0}..
        /// </summary>
        internal static string PIN {
            get {
                return ResourceManager.GetString("PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position sent..
        /// </summary>
        internal static string PositionSent {
            get {
                return ResourceManager.GetString("PositionSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received query..
        /// </summary>
        internal static string QueryReceived {
            get {
                return ResourceManager.GetString("QueryReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received: {0}.
        /// </summary>
        internal static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received command: {0}..
        /// </summary>
        internal static string ReceivedCommand {
            get {
                return ResourceManager.GetString("ReceivedCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received command code: {0}..
        /// </summary>
        internal static string ReceivedCommandCode {
            get {
                return ResourceManager.GetString("ReceivedCommandCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received data..
        /// </summary>
        internal static string ReceivedData {
            get {
                return ResourceManager.GetString("ReceivedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received ID: {0}..
        /// </summary>
        internal static string ReceivedID {
            get {
                return ResourceManager.GetString("ReceivedID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received IMEI: {0}..
        /// </summary>
        internal static string ReceivedImei {
            get {
                return ResourceManager.GetString("ReceivedImei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received length: {0}..
        /// </summary>
        internal static string ReceivedLength {
            get {
                return ResourceManager.GetString("ReceivedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received message: {0}..
        /// </summary>
        internal static string ReceivedMessage {
            get {
                return ResourceManager.GetString("ReceivedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received number: {0}..
        /// </summary>
        internal static string ReceivedNumber {
            get {
                return ResourceManager.GetString("ReceivedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received confirmation..
        /// </summary>
        internal static string ReceivedOk {
            get {
                return ResourceManager.GetString("ReceivedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received packet..
        /// </summary>
        internal static string ReceivedPacket {
            get {
                return ResourceManager.GetString("ReceivedPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received packet length: {0}..
        /// </summary>
        internal static string ReceivedPacketLength {
            get {
                return ResourceManager.GetString("ReceivedPacketLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received settings result..
        /// </summary>
        internal static string ReceivedSettingsResult {
            get {
                return ResourceManager.GetString("ReceivedSettingsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received unknown data..
        /// </summary>
        internal static string ReceivedUnknownData {
            get {
                return ResourceManager.GetString("ReceivedUnknownData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove car: {0}..
        /// </summary>
        internal static string RemoveCar {
            get {
                return ResourceManager.GetString("RemoveCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0}..
        /// </summary>
        internal static string Removing {
            get {
                return ResourceManager.GetString("Removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved settings results..
        /// </summary>
        internal static string SavedSettingsResult {
            get {
                return ResourceManager.GetString("SavedSettingsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending AVR settings..
        /// </summary>
        internal static string SendingAvrSettings {
            get {
                return ResourceManager.GetString("SendingAvrSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending failed..
        /// </summary>
        internal static string SendingFailed {
            get {
                return ResourceManager.GetString("SendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending file..
        /// </summary>
        internal static string SendingFile {
            get {
                return ResourceManager.GetString("SendingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending firmware version..
        /// </summary>
        internal static string SendingFirmwareVersion {
            get {
                return ResourceManager.GetString("SendingFirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending confirmation..
        /// </summary>
        internal static string SendingOK {
            get {
                return ResourceManager.GetString("SendingOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending position to {0}..
        /// </summary>
        internal static string SendingPositionTo {
            get {
                return ResourceManager.GetString("SendingPositionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending random bytes..
        /// </summary>
        internal static string SendingRandomBytes {
            get {
                return ResourceManager.GetString("SendingRandomBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Result..
        /// </summary>
        internal static string SendingResult {
            get {
                return ResourceManager.GetString("SendingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending Telit settings..
        /// </summary>
        internal static string SendingTelitSettings {
            get {
                return ResourceManager.GetString("SendingTelitSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending &apos;U&apos;..
        /// </summary>
        internal static string SendingUpdate {
            get {
                return ResourceManager.GetString("SendingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session id accepted..
        /// </summary>
        internal static string SessionIdAccepted {
            get {
                return ResourceManager.GetString("SessionIdAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session id received:{0}..
        /// </summary>
        internal static string SessionIdReceived {
            get {
                return ResourceManager.GetString("SessionIdReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session id rejected..
        /// </summary>
        internal static string SessionIdRejected {
            get {
                return ResourceManager.GetString("SessionIdRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings select failed..
        /// </summary>
        internal static string SettingsFailed {
            get {
                return ResourceManager.GetString("SettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature accepted..
        /// </summary>
        internal static string SignatureAccepted {
            get {
                return ResourceManager.GetString("SignatureAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature rejected..
        /// </summary>
        internal static string SignatureRejected {
            get {
                return ResourceManager.GetString("SignatureRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signatures: {0}, calculated: {1}..
        /// </summary>
        internal static string SignaturesGotCalculated {
            get {
                return ResourceManager.GetString("SignaturesGotCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too short message..
        /// </summary>
        internal static string TooShortMessage {
            get {
                return ResourceManager.GetString("TooShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too short packet..
        /// </summary>
        internal static string TooShortPacket {
            get {
                return ResourceManager.GetString("TooShortPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown answer..
        /// </summary>
        internal static string UnknownAnswer {
            get {
                return ResourceManager.GetString("UnknownAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command..
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown packet type..
        /// </summary>
        internal static string UnknownPacketType {
            get {
                return ResourceManager.GetString("UnknownPacketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown query..
        /// </summary>
        internal static string UnknownQuery {
            get {
                return ResourceManager.GetString("UnknownQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed...
        /// </summary>
        internal static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update success..
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type: real time position listener..
        /// </summary>
        internal static string UserTypeRealTime {
            get {
                return ResourceManager.GetString("UserTypeRealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for car..
        /// </summary>
        internal static string WaitingForCar {
            get {
                return ResourceManager.GetString("WaitingForCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for key..
        /// </summary>
        internal static string WaitingForKey {
            get {
                return ResourceManager.GetString("WaitingForKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for next command code..
        /// </summary>
        internal static string WaitingForNextCommandCode {
            get {
                return ResourceManager.GetString("WaitingForNextCommandCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for session id..
        /// </summary>
        internal static string WaitingForSessionId {
            get {
                return ResourceManager.GetString("WaitingForSessionId", resourceCulture);
            }
        }
    }
}
