#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="aviscotrackerdb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertgoogle_map(google_map instance);
    partial void Updategoogle_map(google_map instance);
    partial void Deletegoogle_map(google_map instance);
    partial void Insertoutput(output instance);
    partial void Updateoutput(output instance);
    partial void Deleteoutput(output instance);
    partial void InsertTbl_DeviceRegistration(Tbl_DeviceRegistration instance);
    partial void UpdateTbl_DeviceRegistration(Tbl_DeviceRegistration instance);
    partial void DeleteTbl_DeviceRegistration(Tbl_DeviceRegistration instance);
    partial void InsertTbl_User(Tbl_User instance);
    partial void UpdateTbl_User(Tbl_User instance);
    partial void DeleteTbl_User(Tbl_User instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["aviscotrackerdbConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<device_error> device_errors
		{
			get
			{
				return this.GetTable<device_error>();
			}
		}
		
		public System.Data.Linq.Table<telemetry> telemetries
		{
			get
			{
				return this.GetTable<telemetry>();
			}
		}
		
		public System.Data.Linq.Table<google_map> google_maps
		{
			get
			{
				return this.GetTable<google_map>();
			}
		}
		
		public System.Data.Linq.Table<output> outputs
		{
			get
			{
				return this.GetTable<output>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_DeviceRegistration> Tbl_DeviceRegistrations
		{
			get
			{
				return this.GetTable<Tbl_DeviceRegistration>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Log> Tbl_Logs
		{
			get
			{
				return this.GetTable<Tbl_Log>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_User> Tbl_Users
		{
			get
			{
				return this.GetTable<Tbl_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.device_errors")]
	public partial class device_error
	{
		
		private int _id;
		
		private System.Nullable<long> _imei;
		
		private System.Nullable<System.DateTime> _time;
		
		private System.Nullable<System.DateTime> _server_time;
		
		private System.Nullable<short> _function;
		
		private System.Nullable<short> _function_warning;
		
		public device_error()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei", DbType="BigInt")]
		public System.Nullable<long> imei
		{
			get
			{
				return this._imei;
			}
			set
			{
				if ((this._imei != value))
				{
					this._imei = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_server_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> server_time
		{
			get
			{
				return this._server_time;
			}
			set
			{
				if ((this._server_time != value))
				{
					this._server_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[function]", Storage="_function", DbType="SmallInt")]
		public System.Nullable<short> function
		{
			get
			{
				return this._function;
			}
			set
			{
				if ((this._function != value))
				{
					this._function = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_function_warning", DbType="SmallInt")]
		public System.Nullable<short> function_warning
		{
			get
			{
				return this._function_warning;
			}
			set
			{
				if ((this._function_warning != value))
				{
					this._function_warning = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.telemetry")]
	public partial class telemetry
	{
		
		private int _id;
		
		private System.Nullable<long> _imei;
		
		private System.Nullable<short> _acceleration_pedal_position;
		
		private System.Nullable<short> _fuel_level;
		
		private System.Nullable<int> _wheel_speed;
		
		private System.Nullable<int> _engine_speed;
		
		private System.Nullable<long> _total_engine_hours;
		
		private System.Nullable<long> _total_vehicle_distance;
		
		private System.Nullable<int> _analog_inputs0;
		
		private System.Nullable<int> _analog_inputs1;
		
		private System.Nullable<int> _analog_inputs2;
		
		private System.Nullable<int> _analog_inputs3;
		
		private System.Nullable<int> _analog_inputs4;
		
		private System.Nullable<int> _analog_inputs5;
		
		private System.Nullable<int> _analog_inputs6;
		
		private System.Nullable<int> _analog_inputs7;
		
		private System.Nullable<int> _counters0;
		
		private System.Nullable<int> _counters1;
		
		private System.Nullable<int> _counters2;
		
		private System.Nullable<int> _counters3;
		
		private System.Nullable<int> _digital_inputs;
		
		private System.Nullable<int> _fuel_levels0;
		
		private System.Nullable<int> _fuel_levels1;
		
		private System.Nullable<double> _longitude;
		
		private System.Nullable<double> _latitude;
		
		private System.Nullable<short> _speed;
		
		private System.Nullable<short> _satellites;
		
		private System.Nullable<short> _hdop;
		
		private System.Nullable<short> _direction;
		
		private System.Nullable<short> _altitude;
		
		private System.Nullable<double> _odometer;
		
		private System.Nullable<int> _mobile_country_code;
		
		private System.Nullable<short> _mobile_network_code;
		
		private System.Nullable<int> _local_area_code;
		
		private System.Nullable<int> _cell_identifier;
		
		private System.Nullable<short> _timing_advance;
		
		private System.Nullable<short> _recieved_signal_strength;
		
		private System.Nullable<short> _engine_coolant_temperature;
		
		private System.Nullable<int> _j1939_air_temperature;
		
		private System.Nullable<long> _j1939_driver_id;
		
		private System.Nullable<int> _j1939_fuel_rate;
		
		private System.Nullable<int> _j1939_fuel_fms_economy;
		
		private System.Nullable<long> _j1939_fuel_consumption;
		
		private System.Nullable<short> _j1939_axle_number;
		
		private System.Nullable<short> _j1939_tire_number;
		
		private System.Nullable<int> _j1939_axle_weight;
		
		private System.Nullable<short> _j1939_mil_status;
		
		private System.Nullable<short> _j1939_driver1_work;
		
		private System.Nullable<short> _j1939_driver2_work;
		
		private System.Nullable<short> _j1939_motion;
		
		private System.Nullable<short> _j1939_driver1_time;
		
		private System.Nullable<short> _j1939_driver1_crd;
		
		private System.Nullable<short> _j1939_overspeed;
		
		private System.Nullable<short> _j1939_driver2_time;
		
		private System.Nullable<short> _j1939_driver2_crd;
		
		private System.Nullable<short> _j1939_tcoevent;
		
		private System.Nullable<short> _j1939_handl;
		
		private System.Nullable<short> _j1939_perf;
		
		private System.Nullable<short> _j1939_dir;
		
		private System.Nullable<int> _j1939_speed;
		
		private System.Nullable<int> _dtc0;
		
		private System.Nullable<int> _dtc1;
		
		private System.Nullable<int> _dtc2;
		
		private System.Nullable<int> _dtc3;
		
		private System.Nullable<int> _dtc4;
		
		private System.Nullable<int> _dtc5;
		
		private System.Nullable<int> _dtc6;
		
		private System.Nullable<int> _dtc7;
		
		private System.Nullable<int> _dtc8;
		
		private System.Nullable<int> _dtc9;
		
		private System.Nullable<int> _car_in_phone;
		
		private System.Nullable<long> _dallas_id;
		
		private System.Nullable<int> _dallas_temperature;
		
		private System.Nullable<int> _dallas_humidity;
		
		private System.Nullable<int> _lls_lvl_add0;
		
		private System.Nullable<int> _lls_lvl_add1;
		
		private System.Nullable<int> _lls_lvl_add2;
		
		private System.Nullable<int> _lls_lvl_add3;
		
		private System.Nullable<short> _lls_temp_add0;
		
		private System.Nullable<short> _lls_temp_add1;
		
		private System.Nullable<short> _lls_temp_add2;
		
		private System.Nullable<short> _lls_temp_add3;
		
		private System.Nullable<short> _j1979_mil_status;
		
		private System.Nullable<short> _j1979_engine_load;
		
		private System.Nullable<short> _j1979_engine_temperature;
		
		private System.Nullable<short> _j1979_short_fuel_trim1;
		
		private System.Nullable<short> _j1979_long_fuel_trim1;
		
		private System.Nullable<short> _j1979_short_fuel_trim2;
		
		private System.Nullable<short> _j1979_long_fuel_trim2;
		
		private System.Nullable<short> _j1979_fuel_pressure;
		
		private System.Nullable<short> _j1979_map;
		
		private System.Nullable<int> _j1979_rpm;
		
		private System.Nullable<short> _j1979_speed;
		
		private System.Nullable<short> _j1979_air_temp;
		
		private System.Nullable<int> _j1979_maf;
		
		private System.Nullable<short> _j1979_tps;
		
		private System.Nullable<short> _j1979_fuel_level;
		
		private System.Nullable<short> _j1979_rail_pressure;
		
		private System.Nullable<short> _j1979_hybrid_battery_life;
		
		private System.Nullable<int> _j1979_fuel_rate;
		
		private System.Nullable<int> _j1979_dtc0;
		
		private System.Nullable<int> _j1979_dtc1;
		
		private System.Nullable<int> _j1979_dtc2;
		
		private System.Nullable<int> _j1979_dtc3;
		
		private System.Nullable<int> _j1979_dtc4;
		
		private System.Nullable<int> _j1979_dtc5;
		
		private System.Nullable<int> _j1979_dtc6;
		
		private System.Nullable<int> _j1979_dtc7;
		
		private System.Nullable<int> _j1979_dtc8;
		
		private System.Nullable<int> _j1979_dtc9;
		
		private System.Nullable<long> _j1708_engine_hours;
		
		private System.Nullable<long> _j1708_fuel_used;
		
		private System.Nullable<short> _j1708_fuel_level;
		
		private System.Nullable<short> _driving_quality0;
		
		private System.Nullable<short> _driving_quality1;
		
		private System.Nullable<short> _driving_quality2;
		
		private System.Nullable<short> _driving_quality3;
		
		private System.Nullable<short> _driving_quality4;
		
		private System.Nullable<short> _driving_quality5;
		
		private System.Nullable<short> _driving_quality6;
		
		private System.Nullable<short> _driving_quality7;
		
		private System.Nullable<short> _driving_quality8;
		
		private System.Nullable<short> _driving_quality9;
		
		private System.Nullable<short> _driving_quality10;
		
		private System.Nullable<short> _driving_quality11;
		
		private System.Nullable<short> _driving_quality12;
		
		private System.Nullable<short> _driving_quality13;
		
		private System.Nullable<short> _driving_quality14;
		
		private System.Nullable<short> _driving_quality15;
		
		private System.Nullable<short> _driving_quality16;
		
		private System.Nullable<short> _driving_quality17;
		
		private System.Nullable<short> _driving_quality18;
		
		private System.Nullable<short> _driving_quality19;
		
		private System.Nullable<short> _driving_quality20;
		
		private System.Nullable<long> _wiegand26_id;
		
		private System.Nullable<double> _fuel_con_ins;
		
		private System.Nullable<int> _axle_group0;
		
		private System.Nullable<int> _axle_group1;
		
		private System.Nullable<int> _axle_group2;
		
		private System.Nullable<int> _axle_group3;
		
		private System.Nullable<int> _axle_group4;
		
		private System.Nullable<long> _j1939_adblue;
		
		private System.Nullable<long> _prev_digital_inputs;
		
		private System.Nullable<long> _wln_accel_max;
		
		private System.Nullable<long> _wln_brk_max;
		
		private System.Nullable<long> _wln_crn_max;
		
		private System.Nullable<long> _can_message_0700;
		
		private System.Nullable<long> _can_message_0760;
		
		private System.Nullable<long> _one_wire_temp1;
		
		private System.Nullable<long> _one_wire_temp1_id;
		
		private System.Nullable<long> _one_wire_temp2;
		
		private System.Nullable<long> _one_wire_temp2_id;
		
		private System.Nullable<long> _one_wire_temp3;
		
		private System.Nullable<long> _one_wire_temp3_id;
		
		private System.Nullable<long> _one_wire_temp4;
		
		private System.Nullable<long> _one_wire_temp4_id;
		
		private System.Nullable<System.DateTime> _time;
		
		private System.Nullable<long> _total_fuel_used;
		
		public telemetry()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imei", DbType="BigInt")]
		public System.Nullable<long> imei
		{
			get
			{
				return this._imei;
			}
			set
			{
				if ((this._imei != value))
				{
					this._imei = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acceleration_pedal_position", DbType="SmallInt")]
		public System.Nullable<short> acceleration_pedal_position
		{
			get
			{
				return this._acceleration_pedal_position;
			}
			set
			{
				if ((this._acceleration_pedal_position != value))
				{
					this._acceleration_pedal_position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fuel_level", DbType="SmallInt")]
		public System.Nullable<short> fuel_level
		{
			get
			{
				return this._fuel_level;
			}
			set
			{
				if ((this._fuel_level != value))
				{
					this._fuel_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wheel_speed", DbType="Int")]
		public System.Nullable<int> wheel_speed
		{
			get
			{
				return this._wheel_speed;
			}
			set
			{
				if ((this._wheel_speed != value))
				{
					this._wheel_speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_engine_speed", DbType="Int")]
		public System.Nullable<int> engine_speed
		{
			get
			{
				return this._engine_speed;
			}
			set
			{
				if ((this._engine_speed != value))
				{
					this._engine_speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_engine_hours", DbType="BigInt")]
		public System.Nullable<long> total_engine_hours
		{
			get
			{
				return this._total_engine_hours;
			}
			set
			{
				if ((this._total_engine_hours != value))
				{
					this._total_engine_hours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_vehicle_distance", DbType="BigInt")]
		public System.Nullable<long> total_vehicle_distance
		{
			get
			{
				return this._total_vehicle_distance;
			}
			set
			{
				if ((this._total_vehicle_distance != value))
				{
					this._total_vehicle_distance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analog_inputs0", DbType="Int")]
		public System.Nullable<int> analog_inputs0
		{
			get
			{
				return this._analog_inputs0;
			}
			set
			{
				if ((this._analog_inputs0 != value))
				{
					this._analog_inputs0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analog_inputs1", DbType="Int")]
		public System.Nullable<int> analog_inputs1
		{
			get
			{
				return this._analog_inputs1;
			}
			set
			{
				if ((this._analog_inputs1 != value))
				{
					this._analog_inputs1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analog_inputs2", DbType="Int")]
		public System.Nullable<int> analog_inputs2
		{
			get
			{
				return this._analog_inputs2;
			}
			set
			{
				if ((this._analog_inputs2 != value))
				{
					this._analog_inputs2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analog_inputs3", DbType="Int")]
		public System.Nullable<int> analog_inputs3
		{
			get
			{
				return this._analog_inputs3;
			}
			set
			{
				if ((this._analog_inputs3 != value))
				{
					this._analog_inputs3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analog_inputs4", DbType="Int")]
		public System.Nullable<int> analog_inputs4
		{
			get
			{
				return this._analog_inputs4;
			}
			set
			{
				if ((this._analog_inputs4 != value))
				{
					this._analog_inputs4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analog_inputs5", DbType="Int")]
		public System.Nullable<int> analog_inputs5
		{
			get
			{
				return this._analog_inputs5;
			}
			set
			{
				if ((this._analog_inputs5 != value))
				{
					this._analog_inputs5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analog_inputs6", DbType="Int")]
		public System.Nullable<int> analog_inputs6
		{
			get
			{
				return this._analog_inputs6;
			}
			set
			{
				if ((this._analog_inputs6 != value))
				{
					this._analog_inputs6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_analog_inputs7", DbType="Int")]
		public System.Nullable<int> analog_inputs7
		{
			get
			{
				return this._analog_inputs7;
			}
			set
			{
				if ((this._analog_inputs7 != value))
				{
					this._analog_inputs7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_counters0", DbType="Int")]
		public System.Nullable<int> counters0
		{
			get
			{
				return this._counters0;
			}
			set
			{
				if ((this._counters0 != value))
				{
					this._counters0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_counters1", DbType="Int")]
		public System.Nullable<int> counters1
		{
			get
			{
				return this._counters1;
			}
			set
			{
				if ((this._counters1 != value))
				{
					this._counters1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_counters2", DbType="Int")]
		public System.Nullable<int> counters2
		{
			get
			{
				return this._counters2;
			}
			set
			{
				if ((this._counters2 != value))
				{
					this._counters2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_counters3", DbType="Int")]
		public System.Nullable<int> counters3
		{
			get
			{
				return this._counters3;
			}
			set
			{
				if ((this._counters3 != value))
				{
					this._counters3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_digital_inputs", DbType="Int")]
		public System.Nullable<int> digital_inputs
		{
			get
			{
				return this._digital_inputs;
			}
			set
			{
				if ((this._digital_inputs != value))
				{
					this._digital_inputs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fuel_levels0", DbType="Int")]
		public System.Nullable<int> fuel_levels0
		{
			get
			{
				return this._fuel_levels0;
			}
			set
			{
				if ((this._fuel_levels0 != value))
				{
					this._fuel_levels0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fuel_levels1", DbType="Int")]
		public System.Nullable<int> fuel_levels1
		{
			get
			{
				return this._fuel_levels1;
			}
			set
			{
				if ((this._fuel_levels1 != value))
				{
					this._fuel_levels1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="Float")]
		public System.Nullable<double> longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this._longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="Float")]
		public System.Nullable<double> latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this._latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speed", DbType="SmallInt")]
		public System.Nullable<short> speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this._speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_satellites", DbType="SmallInt")]
		public System.Nullable<short> satellites
		{
			get
			{
				return this._satellites;
			}
			set
			{
				if ((this._satellites != value))
				{
					this._satellites = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hdop", DbType="SmallInt")]
		public System.Nullable<short> hdop
		{
			get
			{
				return this._hdop;
			}
			set
			{
				if ((this._hdop != value))
				{
					this._hdop = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direction", DbType="SmallInt")]
		public System.Nullable<short> direction
		{
			get
			{
				return this._direction;
			}
			set
			{
				if ((this._direction != value))
				{
					this._direction = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_altitude", DbType="SmallInt")]
		public System.Nullable<short> altitude
		{
			get
			{
				return this._altitude;
			}
			set
			{
				if ((this._altitude != value))
				{
					this._altitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_odometer", DbType="Float")]
		public System.Nullable<double> odometer
		{
			get
			{
				return this._odometer;
			}
			set
			{
				if ((this._odometer != value))
				{
					this._odometer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile_country_code", DbType="Int")]
		public System.Nullable<int> mobile_country_code
		{
			get
			{
				return this._mobile_country_code;
			}
			set
			{
				if ((this._mobile_country_code != value))
				{
					this._mobile_country_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile_network_code", DbType="SmallInt")]
		public System.Nullable<short> mobile_network_code
		{
			get
			{
				return this._mobile_network_code;
			}
			set
			{
				if ((this._mobile_network_code != value))
				{
					this._mobile_network_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_local_area_code", DbType="Int")]
		public System.Nullable<int> local_area_code
		{
			get
			{
				return this._local_area_code;
			}
			set
			{
				if ((this._local_area_code != value))
				{
					this._local_area_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cell_identifier", DbType="Int")]
		public System.Nullable<int> cell_identifier
		{
			get
			{
				return this._cell_identifier;
			}
			set
			{
				if ((this._cell_identifier != value))
				{
					this._cell_identifier = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_timing_advance", DbType="SmallInt")]
		public System.Nullable<short> timing_advance
		{
			get
			{
				return this._timing_advance;
			}
			set
			{
				if ((this._timing_advance != value))
				{
					this._timing_advance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recieved_signal_strength", DbType="SmallInt")]
		public System.Nullable<short> recieved_signal_strength
		{
			get
			{
				return this._recieved_signal_strength;
			}
			set
			{
				if ((this._recieved_signal_strength != value))
				{
					this._recieved_signal_strength = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_engine_coolant_temperature", DbType="SmallInt")]
		public System.Nullable<short> engine_coolant_temperature
		{
			get
			{
				return this._engine_coolant_temperature;
			}
			set
			{
				if ((this._engine_coolant_temperature != value))
				{
					this._engine_coolant_temperature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_air_temperature", DbType="Int")]
		public System.Nullable<int> j1939_air_temperature
		{
			get
			{
				return this._j1939_air_temperature;
			}
			set
			{
				if ((this._j1939_air_temperature != value))
				{
					this._j1939_air_temperature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_driver_id", DbType="BigInt")]
		public System.Nullable<long> j1939_driver_id
		{
			get
			{
				return this._j1939_driver_id;
			}
			set
			{
				if ((this._j1939_driver_id != value))
				{
					this._j1939_driver_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_fuel_rate", DbType="Int")]
		public System.Nullable<int> j1939_fuel_rate
		{
			get
			{
				return this._j1939_fuel_rate;
			}
			set
			{
				if ((this._j1939_fuel_rate != value))
				{
					this._j1939_fuel_rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_fuel_fms_economy", DbType="Int")]
		public System.Nullable<int> j1939_fuel_fms_economy
		{
			get
			{
				return this._j1939_fuel_fms_economy;
			}
			set
			{
				if ((this._j1939_fuel_fms_economy != value))
				{
					this._j1939_fuel_fms_economy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_fuel_consumption", DbType="BigInt")]
		public System.Nullable<long> j1939_fuel_consumption
		{
			get
			{
				return this._j1939_fuel_consumption;
			}
			set
			{
				if ((this._j1939_fuel_consumption != value))
				{
					this._j1939_fuel_consumption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_axle_number", DbType="SmallInt")]
		public System.Nullable<short> j1939_axle_number
		{
			get
			{
				return this._j1939_axle_number;
			}
			set
			{
				if ((this._j1939_axle_number != value))
				{
					this._j1939_axle_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_tire_number", DbType="SmallInt")]
		public System.Nullable<short> j1939_tire_number
		{
			get
			{
				return this._j1939_tire_number;
			}
			set
			{
				if ((this._j1939_tire_number != value))
				{
					this._j1939_tire_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_axle_weight", DbType="Int")]
		public System.Nullable<int> j1939_axle_weight
		{
			get
			{
				return this._j1939_axle_weight;
			}
			set
			{
				if ((this._j1939_axle_weight != value))
				{
					this._j1939_axle_weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_mil_status", DbType="SmallInt")]
		public System.Nullable<short> j1939_mil_status
		{
			get
			{
				return this._j1939_mil_status;
			}
			set
			{
				if ((this._j1939_mil_status != value))
				{
					this._j1939_mil_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_driver1_work", DbType="SmallInt")]
		public System.Nullable<short> j1939_driver1_work
		{
			get
			{
				return this._j1939_driver1_work;
			}
			set
			{
				if ((this._j1939_driver1_work != value))
				{
					this._j1939_driver1_work = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_driver2_work", DbType="SmallInt")]
		public System.Nullable<short> j1939_driver2_work
		{
			get
			{
				return this._j1939_driver2_work;
			}
			set
			{
				if ((this._j1939_driver2_work != value))
				{
					this._j1939_driver2_work = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_motion", DbType="SmallInt")]
		public System.Nullable<short> j1939_motion
		{
			get
			{
				return this._j1939_motion;
			}
			set
			{
				if ((this._j1939_motion != value))
				{
					this._j1939_motion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_driver1_time", DbType="SmallInt")]
		public System.Nullable<short> j1939_driver1_time
		{
			get
			{
				return this._j1939_driver1_time;
			}
			set
			{
				if ((this._j1939_driver1_time != value))
				{
					this._j1939_driver1_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_driver1_crd", DbType="SmallInt")]
		public System.Nullable<short> j1939_driver1_crd
		{
			get
			{
				return this._j1939_driver1_crd;
			}
			set
			{
				if ((this._j1939_driver1_crd != value))
				{
					this._j1939_driver1_crd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_overspeed", DbType="SmallInt")]
		public System.Nullable<short> j1939_overspeed
		{
			get
			{
				return this._j1939_overspeed;
			}
			set
			{
				if ((this._j1939_overspeed != value))
				{
					this._j1939_overspeed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_driver2_time", DbType="SmallInt")]
		public System.Nullable<short> j1939_driver2_time
		{
			get
			{
				return this._j1939_driver2_time;
			}
			set
			{
				if ((this._j1939_driver2_time != value))
				{
					this._j1939_driver2_time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_driver2_crd", DbType="SmallInt")]
		public System.Nullable<short> j1939_driver2_crd
		{
			get
			{
				return this._j1939_driver2_crd;
			}
			set
			{
				if ((this._j1939_driver2_crd != value))
				{
					this._j1939_driver2_crd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_tcoevent", DbType="SmallInt")]
		public System.Nullable<short> j1939_tcoevent
		{
			get
			{
				return this._j1939_tcoevent;
			}
			set
			{
				if ((this._j1939_tcoevent != value))
				{
					this._j1939_tcoevent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_handl", DbType="SmallInt")]
		public System.Nullable<short> j1939_handl
		{
			get
			{
				return this._j1939_handl;
			}
			set
			{
				if ((this._j1939_handl != value))
				{
					this._j1939_handl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_perf", DbType="SmallInt")]
		public System.Nullable<short> j1939_perf
		{
			get
			{
				return this._j1939_perf;
			}
			set
			{
				if ((this._j1939_perf != value))
				{
					this._j1939_perf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_dir", DbType="SmallInt")]
		public System.Nullable<short> j1939_dir
		{
			get
			{
				return this._j1939_dir;
			}
			set
			{
				if ((this._j1939_dir != value))
				{
					this._j1939_dir = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_speed", DbType="Int")]
		public System.Nullable<int> j1939_speed
		{
			get
			{
				return this._j1939_speed;
			}
			set
			{
				if ((this._j1939_speed != value))
				{
					this._j1939_speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc0", DbType="Int")]
		public System.Nullable<int> dtc0
		{
			get
			{
				return this._dtc0;
			}
			set
			{
				if ((this._dtc0 != value))
				{
					this._dtc0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc1", DbType="Int")]
		public System.Nullable<int> dtc1
		{
			get
			{
				return this._dtc1;
			}
			set
			{
				if ((this._dtc1 != value))
				{
					this._dtc1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc2", DbType="Int")]
		public System.Nullable<int> dtc2
		{
			get
			{
				return this._dtc2;
			}
			set
			{
				if ((this._dtc2 != value))
				{
					this._dtc2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc3", DbType="Int")]
		public System.Nullable<int> dtc3
		{
			get
			{
				return this._dtc3;
			}
			set
			{
				if ((this._dtc3 != value))
				{
					this._dtc3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc4", DbType="Int")]
		public System.Nullable<int> dtc4
		{
			get
			{
				return this._dtc4;
			}
			set
			{
				if ((this._dtc4 != value))
				{
					this._dtc4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc5", DbType="Int")]
		public System.Nullable<int> dtc5
		{
			get
			{
				return this._dtc5;
			}
			set
			{
				if ((this._dtc5 != value))
				{
					this._dtc5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc6", DbType="Int")]
		public System.Nullable<int> dtc6
		{
			get
			{
				return this._dtc6;
			}
			set
			{
				if ((this._dtc6 != value))
				{
					this._dtc6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc7", DbType="Int")]
		public System.Nullable<int> dtc7
		{
			get
			{
				return this._dtc7;
			}
			set
			{
				if ((this._dtc7 != value))
				{
					this._dtc7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc8", DbType="Int")]
		public System.Nullable<int> dtc8
		{
			get
			{
				return this._dtc8;
			}
			set
			{
				if ((this._dtc8 != value))
				{
					this._dtc8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtc9", DbType="Int")]
		public System.Nullable<int> dtc9
		{
			get
			{
				return this._dtc9;
			}
			set
			{
				if ((this._dtc9 != value))
				{
					this._dtc9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_car_in_phone", DbType="Int")]
		public System.Nullable<int> car_in_phone
		{
			get
			{
				return this._car_in_phone;
			}
			set
			{
				if ((this._car_in_phone != value))
				{
					this._car_in_phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dallas_id", DbType="BigInt")]
		public System.Nullable<long> dallas_id
		{
			get
			{
				return this._dallas_id;
			}
			set
			{
				if ((this._dallas_id != value))
				{
					this._dallas_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dallas_temperature", DbType="Int")]
		public System.Nullable<int> dallas_temperature
		{
			get
			{
				return this._dallas_temperature;
			}
			set
			{
				if ((this._dallas_temperature != value))
				{
					this._dallas_temperature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dallas_humidity", DbType="Int")]
		public System.Nullable<int> dallas_humidity
		{
			get
			{
				return this._dallas_humidity;
			}
			set
			{
				if ((this._dallas_humidity != value))
				{
					this._dallas_humidity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lls_lvl_add0", DbType="Int")]
		public System.Nullable<int> lls_lvl_add0
		{
			get
			{
				return this._lls_lvl_add0;
			}
			set
			{
				if ((this._lls_lvl_add0 != value))
				{
					this._lls_lvl_add0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lls_lvl_add1", DbType="Int")]
		public System.Nullable<int> lls_lvl_add1
		{
			get
			{
				return this._lls_lvl_add1;
			}
			set
			{
				if ((this._lls_lvl_add1 != value))
				{
					this._lls_lvl_add1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lls_lvl_add2", DbType="Int")]
		public System.Nullable<int> lls_lvl_add2
		{
			get
			{
				return this._lls_lvl_add2;
			}
			set
			{
				if ((this._lls_lvl_add2 != value))
				{
					this._lls_lvl_add2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lls_lvl_add3", DbType="Int")]
		public System.Nullable<int> lls_lvl_add3
		{
			get
			{
				return this._lls_lvl_add3;
			}
			set
			{
				if ((this._lls_lvl_add3 != value))
				{
					this._lls_lvl_add3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lls_temp_add0", DbType="SmallInt")]
		public System.Nullable<short> lls_temp_add0
		{
			get
			{
				return this._lls_temp_add0;
			}
			set
			{
				if ((this._lls_temp_add0 != value))
				{
					this._lls_temp_add0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lls_temp_add1", DbType="SmallInt")]
		public System.Nullable<short> lls_temp_add1
		{
			get
			{
				return this._lls_temp_add1;
			}
			set
			{
				if ((this._lls_temp_add1 != value))
				{
					this._lls_temp_add1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lls_temp_add2", DbType="SmallInt")]
		public System.Nullable<short> lls_temp_add2
		{
			get
			{
				return this._lls_temp_add2;
			}
			set
			{
				if ((this._lls_temp_add2 != value))
				{
					this._lls_temp_add2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lls_temp_add3", DbType="SmallInt")]
		public System.Nullable<short> lls_temp_add3
		{
			get
			{
				return this._lls_temp_add3;
			}
			set
			{
				if ((this._lls_temp_add3 != value))
				{
					this._lls_temp_add3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_mil_status", DbType="SmallInt")]
		public System.Nullable<short> j1979_mil_status
		{
			get
			{
				return this._j1979_mil_status;
			}
			set
			{
				if ((this._j1979_mil_status != value))
				{
					this._j1979_mil_status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_engine_load", DbType="SmallInt")]
		public System.Nullable<short> j1979_engine_load
		{
			get
			{
				return this._j1979_engine_load;
			}
			set
			{
				if ((this._j1979_engine_load != value))
				{
					this._j1979_engine_load = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_engine_temperature", DbType="SmallInt")]
		public System.Nullable<short> j1979_engine_temperature
		{
			get
			{
				return this._j1979_engine_temperature;
			}
			set
			{
				if ((this._j1979_engine_temperature != value))
				{
					this._j1979_engine_temperature = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_short_fuel_trim1", DbType="SmallInt")]
		public System.Nullable<short> j1979_short_fuel_trim1
		{
			get
			{
				return this._j1979_short_fuel_trim1;
			}
			set
			{
				if ((this._j1979_short_fuel_trim1 != value))
				{
					this._j1979_short_fuel_trim1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_long_fuel_trim1", DbType="SmallInt")]
		public System.Nullable<short> j1979_long_fuel_trim1
		{
			get
			{
				return this._j1979_long_fuel_trim1;
			}
			set
			{
				if ((this._j1979_long_fuel_trim1 != value))
				{
					this._j1979_long_fuel_trim1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_short_fuel_trim2", DbType="SmallInt")]
		public System.Nullable<short> j1979_short_fuel_trim2
		{
			get
			{
				return this._j1979_short_fuel_trim2;
			}
			set
			{
				if ((this._j1979_short_fuel_trim2 != value))
				{
					this._j1979_short_fuel_trim2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_long_fuel_trim2", DbType="SmallInt")]
		public System.Nullable<short> j1979_long_fuel_trim2
		{
			get
			{
				return this._j1979_long_fuel_trim2;
			}
			set
			{
				if ((this._j1979_long_fuel_trim2 != value))
				{
					this._j1979_long_fuel_trim2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_fuel_pressure", DbType="SmallInt")]
		public System.Nullable<short> j1979_fuel_pressure
		{
			get
			{
				return this._j1979_fuel_pressure;
			}
			set
			{
				if ((this._j1979_fuel_pressure != value))
				{
					this._j1979_fuel_pressure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_map", DbType="SmallInt")]
		public System.Nullable<short> j1979_map
		{
			get
			{
				return this._j1979_map;
			}
			set
			{
				if ((this._j1979_map != value))
				{
					this._j1979_map = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_rpm", DbType="Int")]
		public System.Nullable<int> j1979_rpm
		{
			get
			{
				return this._j1979_rpm;
			}
			set
			{
				if ((this._j1979_rpm != value))
				{
					this._j1979_rpm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_speed", DbType="SmallInt")]
		public System.Nullable<short> j1979_speed
		{
			get
			{
				return this._j1979_speed;
			}
			set
			{
				if ((this._j1979_speed != value))
				{
					this._j1979_speed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_air_temp", DbType="SmallInt")]
		public System.Nullable<short> j1979_air_temp
		{
			get
			{
				return this._j1979_air_temp;
			}
			set
			{
				if ((this._j1979_air_temp != value))
				{
					this._j1979_air_temp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_maf", DbType="Int")]
		public System.Nullable<int> j1979_maf
		{
			get
			{
				return this._j1979_maf;
			}
			set
			{
				if ((this._j1979_maf != value))
				{
					this._j1979_maf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_tps", DbType="SmallInt")]
		public System.Nullable<short> j1979_tps
		{
			get
			{
				return this._j1979_tps;
			}
			set
			{
				if ((this._j1979_tps != value))
				{
					this._j1979_tps = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_fuel_level", DbType="SmallInt")]
		public System.Nullable<short> j1979_fuel_level
		{
			get
			{
				return this._j1979_fuel_level;
			}
			set
			{
				if ((this._j1979_fuel_level != value))
				{
					this._j1979_fuel_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_rail_pressure", DbType="SmallInt")]
		public System.Nullable<short> j1979_rail_pressure
		{
			get
			{
				return this._j1979_rail_pressure;
			}
			set
			{
				if ((this._j1979_rail_pressure != value))
				{
					this._j1979_rail_pressure = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_hybrid_battery_life", DbType="SmallInt")]
		public System.Nullable<short> j1979_hybrid_battery_life
		{
			get
			{
				return this._j1979_hybrid_battery_life;
			}
			set
			{
				if ((this._j1979_hybrid_battery_life != value))
				{
					this._j1979_hybrid_battery_life = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_fuel_rate", DbType="Int")]
		public System.Nullable<int> j1979_fuel_rate
		{
			get
			{
				return this._j1979_fuel_rate;
			}
			set
			{
				if ((this._j1979_fuel_rate != value))
				{
					this._j1979_fuel_rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_dtc0", DbType="Int")]
		public System.Nullable<int> j1979_dtc0
		{
			get
			{
				return this._j1979_dtc0;
			}
			set
			{
				if ((this._j1979_dtc0 != value))
				{
					this._j1979_dtc0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_dtc1", DbType="Int")]
		public System.Nullable<int> j1979_dtc1
		{
			get
			{
				return this._j1979_dtc1;
			}
			set
			{
				if ((this._j1979_dtc1 != value))
				{
					this._j1979_dtc1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_dtc2", DbType="Int")]
		public System.Nullable<int> j1979_dtc2
		{
			get
			{
				return this._j1979_dtc2;
			}
			set
			{
				if ((this._j1979_dtc2 != value))
				{
					this._j1979_dtc2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_dtc3", DbType="Int")]
		public System.Nullable<int> j1979_dtc3
		{
			get
			{
				return this._j1979_dtc3;
			}
			set
			{
				if ((this._j1979_dtc3 != value))
				{
					this._j1979_dtc3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_dtc4", DbType="Int")]
		public System.Nullable<int> j1979_dtc4
		{
			get
			{
				return this._j1979_dtc4;
			}
			set
			{
				if ((this._j1979_dtc4 != value))
				{
					this._j1979_dtc4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_dtc5", DbType="Int")]
		public System.Nullable<int> j1979_dtc5
		{
			get
			{
				return this._j1979_dtc5;
			}
			set
			{
				if ((this._j1979_dtc5 != value))
				{
					this._j1979_dtc5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_dtc6", DbType="Int")]
		public System.Nullable<int> j1979_dtc6
		{
			get
			{
				return this._j1979_dtc6;
			}
			set
			{
				if ((this._j1979_dtc6 != value))
				{
					this._j1979_dtc6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_dtc7", DbType="Int")]
		public System.Nullable<int> j1979_dtc7
		{
			get
			{
				return this._j1979_dtc7;
			}
			set
			{
				if ((this._j1979_dtc7 != value))
				{
					this._j1979_dtc7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_dtc8", DbType="Int")]
		public System.Nullable<int> j1979_dtc8
		{
			get
			{
				return this._j1979_dtc8;
			}
			set
			{
				if ((this._j1979_dtc8 != value))
				{
					this._j1979_dtc8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1979_dtc9", DbType="Int")]
		public System.Nullable<int> j1979_dtc9
		{
			get
			{
				return this._j1979_dtc9;
			}
			set
			{
				if ((this._j1979_dtc9 != value))
				{
					this._j1979_dtc9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1708_engine_hours", DbType="BigInt")]
		public System.Nullable<long> j1708_engine_hours
		{
			get
			{
				return this._j1708_engine_hours;
			}
			set
			{
				if ((this._j1708_engine_hours != value))
				{
					this._j1708_engine_hours = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1708_fuel_used", DbType="BigInt")]
		public System.Nullable<long> j1708_fuel_used
		{
			get
			{
				return this._j1708_fuel_used;
			}
			set
			{
				if ((this._j1708_fuel_used != value))
				{
					this._j1708_fuel_used = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1708_fuel_level", DbType="SmallInt")]
		public System.Nullable<short> j1708_fuel_level
		{
			get
			{
				return this._j1708_fuel_level;
			}
			set
			{
				if ((this._j1708_fuel_level != value))
				{
					this._j1708_fuel_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality0", DbType="SmallInt")]
		public System.Nullable<short> driving_quality0
		{
			get
			{
				return this._driving_quality0;
			}
			set
			{
				if ((this._driving_quality0 != value))
				{
					this._driving_quality0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality1", DbType="SmallInt")]
		public System.Nullable<short> driving_quality1
		{
			get
			{
				return this._driving_quality1;
			}
			set
			{
				if ((this._driving_quality1 != value))
				{
					this._driving_quality1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality2", DbType="SmallInt")]
		public System.Nullable<short> driving_quality2
		{
			get
			{
				return this._driving_quality2;
			}
			set
			{
				if ((this._driving_quality2 != value))
				{
					this._driving_quality2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality3", DbType="SmallInt")]
		public System.Nullable<short> driving_quality3
		{
			get
			{
				return this._driving_quality3;
			}
			set
			{
				if ((this._driving_quality3 != value))
				{
					this._driving_quality3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality4", DbType="SmallInt")]
		public System.Nullable<short> driving_quality4
		{
			get
			{
				return this._driving_quality4;
			}
			set
			{
				if ((this._driving_quality4 != value))
				{
					this._driving_quality4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality5", DbType="SmallInt")]
		public System.Nullable<short> driving_quality5
		{
			get
			{
				return this._driving_quality5;
			}
			set
			{
				if ((this._driving_quality5 != value))
				{
					this._driving_quality5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality6", DbType="SmallInt")]
		public System.Nullable<short> driving_quality6
		{
			get
			{
				return this._driving_quality6;
			}
			set
			{
				if ((this._driving_quality6 != value))
				{
					this._driving_quality6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality7", DbType="SmallInt")]
		public System.Nullable<short> driving_quality7
		{
			get
			{
				return this._driving_quality7;
			}
			set
			{
				if ((this._driving_quality7 != value))
				{
					this._driving_quality7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality8", DbType="SmallInt")]
		public System.Nullable<short> driving_quality8
		{
			get
			{
				return this._driving_quality8;
			}
			set
			{
				if ((this._driving_quality8 != value))
				{
					this._driving_quality8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality9", DbType="SmallInt")]
		public System.Nullable<short> driving_quality9
		{
			get
			{
				return this._driving_quality9;
			}
			set
			{
				if ((this._driving_quality9 != value))
				{
					this._driving_quality9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality10", DbType="SmallInt")]
		public System.Nullable<short> driving_quality10
		{
			get
			{
				return this._driving_quality10;
			}
			set
			{
				if ((this._driving_quality10 != value))
				{
					this._driving_quality10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality11", DbType="SmallInt")]
		public System.Nullable<short> driving_quality11
		{
			get
			{
				return this._driving_quality11;
			}
			set
			{
				if ((this._driving_quality11 != value))
				{
					this._driving_quality11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality12", DbType="SmallInt")]
		public System.Nullable<short> driving_quality12
		{
			get
			{
				return this._driving_quality12;
			}
			set
			{
				if ((this._driving_quality12 != value))
				{
					this._driving_quality12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality13", DbType="SmallInt")]
		public System.Nullable<short> driving_quality13
		{
			get
			{
				return this._driving_quality13;
			}
			set
			{
				if ((this._driving_quality13 != value))
				{
					this._driving_quality13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality14", DbType="SmallInt")]
		public System.Nullable<short> driving_quality14
		{
			get
			{
				return this._driving_quality14;
			}
			set
			{
				if ((this._driving_quality14 != value))
				{
					this._driving_quality14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality15", DbType="SmallInt")]
		public System.Nullable<short> driving_quality15
		{
			get
			{
				return this._driving_quality15;
			}
			set
			{
				if ((this._driving_quality15 != value))
				{
					this._driving_quality15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality16", DbType="SmallInt")]
		public System.Nullable<short> driving_quality16
		{
			get
			{
				return this._driving_quality16;
			}
			set
			{
				if ((this._driving_quality16 != value))
				{
					this._driving_quality16 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality17", DbType="SmallInt")]
		public System.Nullable<short> driving_quality17
		{
			get
			{
				return this._driving_quality17;
			}
			set
			{
				if ((this._driving_quality17 != value))
				{
					this._driving_quality17 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality18", DbType="SmallInt")]
		public System.Nullable<short> driving_quality18
		{
			get
			{
				return this._driving_quality18;
			}
			set
			{
				if ((this._driving_quality18 != value))
				{
					this._driving_quality18 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality19", DbType="SmallInt")]
		public System.Nullable<short> driving_quality19
		{
			get
			{
				return this._driving_quality19;
			}
			set
			{
				if ((this._driving_quality19 != value))
				{
					this._driving_quality19 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_driving_quality20", DbType="SmallInt")]
		public System.Nullable<short> driving_quality20
		{
			get
			{
				return this._driving_quality20;
			}
			set
			{
				if ((this._driving_quality20 != value))
				{
					this._driving_quality20 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wiegand26_id", DbType="BigInt")]
		public System.Nullable<long> wiegand26_id
		{
			get
			{
				return this._wiegand26_id;
			}
			set
			{
				if ((this._wiegand26_id != value))
				{
					this._wiegand26_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fuel_con_ins", DbType="Float")]
		public System.Nullable<double> fuel_con_ins
		{
			get
			{
				return this._fuel_con_ins;
			}
			set
			{
				if ((this._fuel_con_ins != value))
				{
					this._fuel_con_ins = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_axle_group0", DbType="Int")]
		public System.Nullable<int> axle_group0
		{
			get
			{
				return this._axle_group0;
			}
			set
			{
				if ((this._axle_group0 != value))
				{
					this._axle_group0 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_axle_group1", DbType="Int")]
		public System.Nullable<int> axle_group1
		{
			get
			{
				return this._axle_group1;
			}
			set
			{
				if ((this._axle_group1 != value))
				{
					this._axle_group1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_axle_group2", DbType="Int")]
		public System.Nullable<int> axle_group2
		{
			get
			{
				return this._axle_group2;
			}
			set
			{
				if ((this._axle_group2 != value))
				{
					this._axle_group2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_axle_group3", DbType="Int")]
		public System.Nullable<int> axle_group3
		{
			get
			{
				return this._axle_group3;
			}
			set
			{
				if ((this._axle_group3 != value))
				{
					this._axle_group3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_axle_group4", DbType="Int")]
		public System.Nullable<int> axle_group4
		{
			get
			{
				return this._axle_group4;
			}
			set
			{
				if ((this._axle_group4 != value))
				{
					this._axle_group4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_j1939_adblue", DbType="BigInt")]
		public System.Nullable<long> j1939_adblue
		{
			get
			{
				return this._j1939_adblue;
			}
			set
			{
				if ((this._j1939_adblue != value))
				{
					this._j1939_adblue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prev_digital_inputs", DbType="BigInt")]
		public System.Nullable<long> prev_digital_inputs
		{
			get
			{
				return this._prev_digital_inputs;
			}
			set
			{
				if ((this._prev_digital_inputs != value))
				{
					this._prev_digital_inputs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wln_accel_max", DbType="BigInt")]
		public System.Nullable<long> wln_accel_max
		{
			get
			{
				return this._wln_accel_max;
			}
			set
			{
				if ((this._wln_accel_max != value))
				{
					this._wln_accel_max = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wln_brk_max", DbType="BigInt")]
		public System.Nullable<long> wln_brk_max
		{
			get
			{
				return this._wln_brk_max;
			}
			set
			{
				if ((this._wln_brk_max != value))
				{
					this._wln_brk_max = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wln_crn_max", DbType="BigInt")]
		public System.Nullable<long> wln_crn_max
		{
			get
			{
				return this._wln_crn_max;
			}
			set
			{
				if ((this._wln_crn_max != value))
				{
					this._wln_crn_max = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_can_message_0700", DbType="BigInt")]
		public System.Nullable<long> can_message_0700
		{
			get
			{
				return this._can_message_0700;
			}
			set
			{
				if ((this._can_message_0700 != value))
				{
					this._can_message_0700 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_can_message_0760", DbType="BigInt")]
		public System.Nullable<long> can_message_0760
		{
			get
			{
				return this._can_message_0760;
			}
			set
			{
				if ((this._can_message_0760 != value))
				{
					this._can_message_0760 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_one_wire_temp1", DbType="BigInt")]
		public System.Nullable<long> one_wire_temp1
		{
			get
			{
				return this._one_wire_temp1;
			}
			set
			{
				if ((this._one_wire_temp1 != value))
				{
					this._one_wire_temp1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_one_wire_temp1_id", DbType="BigInt")]
		public System.Nullable<long> one_wire_temp1_id
		{
			get
			{
				return this._one_wire_temp1_id;
			}
			set
			{
				if ((this._one_wire_temp1_id != value))
				{
					this._one_wire_temp1_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_one_wire_temp2", DbType="BigInt")]
		public System.Nullable<long> one_wire_temp2
		{
			get
			{
				return this._one_wire_temp2;
			}
			set
			{
				if ((this._one_wire_temp2 != value))
				{
					this._one_wire_temp2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_one_wire_temp2_id", DbType="BigInt")]
		public System.Nullable<long> one_wire_temp2_id
		{
			get
			{
				return this._one_wire_temp2_id;
			}
			set
			{
				if ((this._one_wire_temp2_id != value))
				{
					this._one_wire_temp2_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_one_wire_temp3", DbType="BigInt")]
		public System.Nullable<long> one_wire_temp3
		{
			get
			{
				return this._one_wire_temp3;
			}
			set
			{
				if ((this._one_wire_temp3 != value))
				{
					this._one_wire_temp3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_one_wire_temp3_id", DbType="BigInt")]
		public System.Nullable<long> one_wire_temp3_id
		{
			get
			{
				return this._one_wire_temp3_id;
			}
			set
			{
				if ((this._one_wire_temp3_id != value))
				{
					this._one_wire_temp3_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_one_wire_temp4", DbType="BigInt")]
		public System.Nullable<long> one_wire_temp4
		{
			get
			{
				return this._one_wire_temp4;
			}
			set
			{
				if ((this._one_wire_temp4 != value))
				{
					this._one_wire_temp4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_one_wire_temp4_id", DbType="BigInt")]
		public System.Nullable<long> one_wire_temp4_id
		{
			get
			{
				return this._one_wire_temp4_id;
			}
			set
			{
				if ((this._one_wire_temp4_id != value))
				{
					this._one_wire_temp4_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this._time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_fuel_used", DbType="BigInt")]
		public System.Nullable<long> total_fuel_used
		{
			get
			{
				return this._total_fuel_used;
			}
			set
			{
				if ((this._total_fuel_used != value))
				{
					this._total_fuel_used = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.google_map")]
	public partial class google_map : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Rating;
		
		private string _Address;
		
		private double _Lat;
		
		private System.Nullable<double> _Long;
		
		private System.Nullable<int> _stetus;
		
		private System.Nullable<System.DateTime> _Date1;
		
		private System.Nullable<double> _speed;
		
		private System.Nullable<int> _UserId;
		
		private EntityRef<Tbl_User> _Tbl_User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRatingChanging(System.Nullable<int> value);
    partial void OnRatingChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnLatChanging(double value);
    partial void OnLatChanged();
    partial void OnLongChanging(System.Nullable<double> value);
    partial void OnLongChanged();
    partial void OnstetusChanging(System.Nullable<int> value);
    partial void OnstetusChanged();
    partial void OnDate1Changing(System.Nullable<System.DateTime> value);
    partial void OnDate1Changed();
    partial void OnspeedChanging(System.Nullable<double> value);
    partial void OnspeedChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    #endregion
		
		public google_map()
		{
			this._Tbl_User = default(EntityRef<Tbl_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating", DbType="Int")]
		public System.Nullable<int> Rating
		{
			get
			{
				return this._Rating;
			}
			set
			{
				if ((this._Rating != value))
				{
					this.OnRatingChanging(value);
					this.SendPropertyChanging();
					this._Rating = value;
					this.SendPropertyChanged("Rating");
					this.OnRatingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="Float NOT NULL")]
		public double Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this.OnLatChanging(value);
					this.SendPropertyChanging();
					this._Lat = value;
					this.SendPropertyChanged("Lat");
					this.OnLatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Long", DbType="Float")]
		public System.Nullable<double> Long
		{
			get
			{
				return this._Long;
			}
			set
			{
				if ((this._Long != value))
				{
					this.OnLongChanging(value);
					this.SendPropertyChanging();
					this._Long = value;
					this.SendPropertyChanged("Long");
					this.OnLongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stetus", DbType="Int")]
		public System.Nullable<int> stetus
		{
			get
			{
				return this._stetus;
			}
			set
			{
				if ((this._stetus != value))
				{
					this.OnstetusChanging(value);
					this.SendPropertyChanging();
					this._stetus = value;
					this.SendPropertyChanged("stetus");
					this.OnstetusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date1", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date1
		{
			get
			{
				return this._Date1;
			}
			set
			{
				if ((this._Date1 != value))
				{
					this.OnDate1Changing(value);
					this.SendPropertyChanging();
					this._Date1 = value;
					this.SendPropertyChanged("Date1");
					this.OnDate1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_speed", DbType="Float")]
		public System.Nullable<double> speed
		{
			get
			{
				return this._speed;
			}
			set
			{
				if ((this._speed != value))
				{
					this.OnspeedChanging(value);
					this.SendPropertyChanging();
					this._speed = value;
					this.SendPropertyChanged("speed");
					this.OnspeedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._Tbl_User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_google_map", Storage="_Tbl_User", ThisKey="UserId", OtherKey="UserID", IsForeignKey=true)]
		public Tbl_User Tbl_User
		{
			get
			{
				return this._Tbl_User.Entity;
			}
			set
			{
				Tbl_User previousValue = this._Tbl_User.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_User.Entity = null;
						previousValue.google_maps.Remove(this);
					}
					this._Tbl_User.Entity = value;
					if ((value != null))
					{
						value.google_maps.Add(this);
						this._UserId = value.UserID;
					}
					else
					{
						this._UserId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.outputs")]
	public partial class output : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<short> _output_id;
		
		private System.Data.Linq.Binary _output_data;
		
		private System.Nullable<short> _status;
		
		private System.Nullable<System.DateTime> _expiration_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onoutput_idChanging(System.Nullable<short> value);
    partial void Onoutput_idChanged();
    partial void Onoutput_dataChanging(System.Data.Linq.Binary value);
    partial void Onoutput_dataChanged();
    partial void OnstatusChanging(System.Nullable<short> value);
    partial void OnstatusChanged();
    partial void Onexpiration_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onexpiration_dateChanged();
    #endregion
		
		public output()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_output_id", DbType="SmallInt")]
		public System.Nullable<short> output_id
		{
			get
			{
				return this._output_id;
			}
			set
			{
				if ((this._output_id != value))
				{
					this.Onoutput_idChanging(value);
					this.SendPropertyChanging();
					this._output_id = value;
					this.SendPropertyChanged("output_id");
					this.Onoutput_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_output_data", DbType="VarBinary(50)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary output_data
		{
			get
			{
				return this._output_data;
			}
			set
			{
				if ((this._output_data != value))
				{
					this.Onoutput_dataChanging(value);
					this.SendPropertyChanging();
					this._output_data = value;
					this.SendPropertyChanged("output_data");
					this.Onoutput_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="SmallInt")]
		public System.Nullable<short> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expiration_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> expiration_date
		{
			get
			{
				return this._expiration_date;
			}
			set
			{
				if ((this._expiration_date != value))
				{
					this.Onexpiration_dateChanging(value);
					this.SendPropertyChanging();
					this._expiration_date = value;
					this.SendPropertyChanged("expiration_date");
					this.Onexpiration_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_DeviceRegistration")]
	public partial class Tbl_DeviceRegistration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DeviceName;
		
		private long _DeviceIMEI;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<int> _UserId;
		
		private string _Vehicle_Type;
		
		private string _SimNo;
		
		private string _APN;
		
		private string _DeviceModel;
		
		private string _stetus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeviceNameChanging(string value);
    partial void OnDeviceNameChanged();
    partial void OnDeviceIMEIChanging(long value);
    partial void OnDeviceIMEIChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnUserIdChanging(System.Nullable<int> value);
    partial void OnUserIdChanged();
    partial void OnVehicle_TypeChanging(string value);
    partial void OnVehicle_TypeChanged();
    partial void OnSimNoChanging(string value);
    partial void OnSimNoChanged();
    partial void OnAPNChanging(string value);
    partial void OnAPNChanged();
    partial void OnDeviceModelChanging(string value);
    partial void OnDeviceModelChanged();
    partial void OnstetusChanging(string value);
    partial void OnstetusChanged();
    #endregion
		
		public Tbl_DeviceRegistration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceName", DbType="NVarChar(50)")]
		public string DeviceName
		{
			get
			{
				return this._DeviceName;
			}
			set
			{
				if ((this._DeviceName != value))
				{
					this.OnDeviceNameChanging(value);
					this.SendPropertyChanging();
					this._DeviceName = value;
					this.SendPropertyChanged("DeviceName");
					this.OnDeviceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceIMEI", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long DeviceIMEI
		{
			get
			{
				return this._DeviceIMEI;
			}
			set
			{
				if ((this._DeviceIMEI != value))
				{
					this.OnDeviceIMEIChanging(value);
					this.SendPropertyChanging();
					this._DeviceIMEI = value;
					this.SendPropertyChanged("DeviceIMEI");
					this.OnDeviceIMEIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="Int")]
		public System.Nullable<int> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vehicle_Type", DbType="NVarChar(20)")]
		public string Vehicle_Type
		{
			get
			{
				return this._Vehicle_Type;
			}
			set
			{
				if ((this._Vehicle_Type != value))
				{
					this.OnVehicle_TypeChanging(value);
					this.SendPropertyChanging();
					this._Vehicle_Type = value;
					this.SendPropertyChanged("Vehicle_Type");
					this.OnVehicle_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SimNo", DbType="NChar(11)")]
		public string SimNo
		{
			get
			{
				return this._SimNo;
			}
			set
			{
				if ((this._SimNo != value))
				{
					this.OnSimNoChanging(value);
					this.SendPropertyChanging();
					this._SimNo = value;
					this.SendPropertyChanged("SimNo");
					this.OnSimNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APN", DbType="NChar(30)")]
		public string APN
		{
			get
			{
				return this._APN;
			}
			set
			{
				if ((this._APN != value))
				{
					this.OnAPNChanging(value);
					this.SendPropertyChanging();
					this._APN = value;
					this.SendPropertyChanged("APN");
					this.OnAPNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeviceModel", DbType="NVarChar(50)")]
		public string DeviceModel
		{
			get
			{
				return this._DeviceModel;
			}
			set
			{
				if ((this._DeviceModel != value))
				{
					this.OnDeviceModelChanging(value);
					this.SendPropertyChanging();
					this._DeviceModel = value;
					this.SendPropertyChanged("DeviceModel");
					this.OnDeviceModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stetus", DbType="NChar(10)")]
		public string stetus
		{
			get
			{
				return this._stetus;
			}
			set
			{
				if ((this._stetus != value))
				{
					this.OnstetusChanging(value);
					this.SendPropertyChanging();
					this._stetus = value;
					this.SendPropertyChanged("stetus");
					this.OnstetusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Log")]
	public partial class Tbl_Log
	{
		
		private System.Nullable<int> _Id;
		
		private string _Lat;
		
		private string _Long;
		
		private System.Nullable<System.DateTime> _Date;
		
		private string _fuel;
		
		public Tbl_Log()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int")]
		public System.Nullable<int> Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="NVarChar(50)")]
		public string Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this._Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Long", DbType="NVarChar(50)")]
		public string Long
		{
			get
			{
				return this._Long;
			}
			set
			{
				if ((this._Long != value))
				{
					this._Long = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fuel", DbType="NChar(10)")]
		public string fuel
		{
			get
			{
				return this._fuel;
			}
			set
			{
				if ((this._fuel != value))
				{
					this._fuel = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_User")]
	public partial class Tbl_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _username;
		
		private string _Password;
		
		private string _EMail;
		
		private string _Companyname;
		
		private string _ContactNo;
		
		private string _Name;
		
		private EntitySet<google_map> _google_maps;
		
		private EntityRef<Tbl_User> _Tbl_User2;
		
		private EntityRef<Tbl_User> _Tbl_User1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnCompanynameChanging(string value);
    partial void OnCompanynameChanged();
    partial void OnContactNoChanging(string value);
    partial void OnContactNoChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public Tbl_User()
		{
			this._google_maps = new EntitySet<google_map>(new Action<google_map>(this.attach_google_maps), new Action<google_map>(this.detach_google_maps));
			this._Tbl_User2 = default(EntityRef<Tbl_User>);
			this._Tbl_User1 = default(EntityRef<Tbl_User>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					if (this._Tbl_User1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NChar(30)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(50)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Companyname", DbType="NVarChar(50)")]
		public string Companyname
		{
			get
			{
				return this._Companyname;
			}
			set
			{
				if ((this._Companyname != value))
				{
					this.OnCompanynameChanging(value);
					this.SendPropertyChanging();
					this._Companyname = value;
					this.SendPropertyChanged("Companyname");
					this.OnCompanynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactNo", DbType="NChar(11)")]
		public string ContactNo
		{
			get
			{
				return this._ContactNo;
			}
			set
			{
				if ((this._ContactNo != value))
				{
					this.OnContactNoChanging(value);
					this.SendPropertyChanging();
					this._ContactNo = value;
					this.SendPropertyChanged("ContactNo");
					this.OnContactNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_google_map", Storage="_google_maps", ThisKey="UserID", OtherKey="UserId")]
		public EntitySet<google_map> google_maps
		{
			get
			{
				return this._google_maps;
			}
			set
			{
				this._google_maps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_Tbl_User", Storage="_Tbl_User2", ThisKey="UserID", OtherKey="UserID", IsUnique=true, IsForeignKey=false)]
		public Tbl_User Tbl_User2
		{
			get
			{
				return this._Tbl_User2.Entity;
			}
			set
			{
				Tbl_User previousValue = this._Tbl_User2.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_User2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_User2.Entity = null;
						previousValue.Tbl_User1 = null;
					}
					this._Tbl_User2.Entity = value;
					if ((value != null))
					{
						value.Tbl_User1 = this;
					}
					this.SendPropertyChanged("Tbl_User2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_User_Tbl_User", Storage="_Tbl_User1", ThisKey="UserID", OtherKey="UserID", IsForeignKey=true)]
		public Tbl_User Tbl_User1
		{
			get
			{
				return this._Tbl_User1.Entity;
			}
			set
			{
				Tbl_User previousValue = this._Tbl_User1.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_User1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_User1.Entity = null;
						previousValue.Tbl_User2 = null;
					}
					this._Tbl_User1.Entity = value;
					if ((value != null))
					{
						value.Tbl_User2 = this;
						this._UserID = value.UserID;
					}
					else
					{
						this._UserID = default(int);
					}
					this.SendPropertyChanged("Tbl_User1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_google_maps(google_map entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_User = this;
		}
		
		private void detach_google_maps(google_map entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_User = null;
		}
	}
}
#pragma warning restore 1591
